-- auto-generated by Cube's TitanBarWalletItemsGenerator tool at 2024-07-02 17:34:46 UTC
_G.WalletItems = {
  [1879092849] = { ["itemIdHex"] = "0x7000ae71"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Broken Arnorian Pauldrons
  [1879092850] = { ["itemIdHex"] = "0x7000ae72"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Broken Arnorian Shirt
  [1879092851] = { ["itemIdHex"] = "0x7000ae73"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Broken Arnorian Leggings
  [1879092852] = { ["itemIdHex"] = "0x7000ae74"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Arnorian Armour Fragments
  [1879092853] = { ["itemIdHex"] = "0x7000ae75"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Battered Arnorian Armour
  [1879093652] = { ["itemIdHex"] = "0x7000b194"; ["itemClass"] = 27; ["category"] = 13; ["shared"] = true; }; -- Bottle of Ale
  [1879093653] = { ["itemIdHex"] = "0x7000b195"; ["itemClass"] = 27; ["category"] = 13; ["shared"] = true; }; -- Keg of Cram
  [1879095717] = { ["itemIdHex"] = "0x7000b9a5"; ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Dull Spirit Stone
  [1879095718] = { ["itemIdHex"] = "0x7000b9a6"; ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Glimmering Spirit Stone
  [1879095719] = { ["itemIdHex"] = "0x7000b9a7"; ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Luminous Spirit Stone
  [1879098157] = { ["itemIdHex"] = "0x7000c32d"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Opal
  [1879098158] = { ["itemIdHex"] = "0x7000c32e"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Sparkling Diamond
  [1879098159] = { ["itemIdHex"] = "0x7000c32f"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Fiery Quartz
  [1879098160] = { ["itemIdHex"] = "0x7000c330"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dazzling Emerald
  [1879098161] = { ["itemIdHex"] = "0x7000c331"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Near Perfect Sapphire
  [1879098162] = { ["itemIdHex"] = "0x7000c332"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Glinting Amethyst
  [1879098163] = { ["itemIdHex"] = "0x7000c333"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Glowing Red Ruby
  [1879098172] = { ["itemIdHex"] = "0x7000c33c"; ["itemClass"] = 178; ["category"] = 10; }; -- Rift-iron Coin
  [1879098260] = { ["itemIdHex"] = "0x7000c394"; ["itemClass"] = 178; ["category"] = 13; }; -- Faultless Geode
  [1879098261] = { ["itemIdHex"] = "0x7000c395"; ["itemClass"] = 178; ["category"] = 13; }; -- Pristine Geode
  [1879098262] = { ["itemIdHex"] = "0x7000c396"; ["itemClass"] = 178; ["category"] = 13; }; -- Cracked Geode
  [1879098263] = { ["itemIdHex"] = "0x7000c397"; ["itemClass"] = 178; ["category"] = 13; }; -- Elegant Scroll
  [1879098264] = { ["itemIdHex"] = "0x7000c398"; ["itemClass"] = 178; ["category"] = 13; }; -- Well-written Scroll
  [1879098265] = { ["itemIdHex"] = "0x7000c399"; ["itemClass"] = 178; ["category"] = 13; }; -- Unimpressive Scroll
  [1879098266] = { ["itemIdHex"] = "0x7000c39a"; ["itemClass"] = 178; ["category"] = 13; }; -- Large Apple
  [1879098267] = { ["itemIdHex"] = "0x7000c39b"; ["itemClass"] = 178; ["category"] = 13; }; -- Medium Apple
  [1879098268] = { ["itemIdHex"] = "0x7000c39c"; ["itemClass"] = 178; ["category"] = 13; }; -- Small Apple
  [1879098269] = { ["itemIdHex"] = "0x7000c39d"; ["itemClass"] = 178; ["category"] = 13; }; -- Large Pumpkin
  [1879098270] = { ["itemIdHex"] = "0x7000c39e"; ["itemClass"] = 178; ["category"] = 13; }; -- Medium Pumpkin
  [1879098271] = { ["itemIdHex"] = "0x7000c39f"; ["itemClass"] = 178; ["category"] = 13; }; -- Small Pumpkin
  [1879098272] = { ["itemIdHex"] = "0x7000c3a0"; ["itemClass"] = 178; ["category"] = 13; }; -- Fall Festival Token
  [1879098864] = { ["itemIdHex"] = "0x7000c5f0"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Barghest Corpse
  [1879098865] = { ["itemIdHex"] = "0x7000c5f1"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Black-bear Corpse
  [1879098866] = { ["itemIdHex"] = "0x7000c5f2"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Brown-bear Corpse
  [1879098867] = { ["itemIdHex"] = "0x7000c5f3"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Cave-troll Head
  [1879098868] = { ["itemIdHex"] = "0x7000c5f4"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Warg Corpse
  [1879098869] = { ["itemIdHex"] = "0x7000c5f5"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged White-wolf Corpse
  [1879099326] = { ["itemIdHex"] = "0x7000c7be"; ["itemClass"] = 178; ["category"] = 10; }; -- Obsidian Rock-shard
  [1879099340] = { ["itemIdHex"] = "0x7000c7cc"; ["itemClass"] = 178; ["category"] = 10; }; -- Scrap of Rift-iron Ore
  [1879101765] = { ["itemIdHex"] = "0x7000d145"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Harvestmath Race Token
  [1879103035] = { ["itemIdHex"] = "0x7000d63b"; ["itemClass"] = 178; ["category"] = 12; }; -- Arm of Lagmas
  [1879103036] = { ["itemIdHex"] = "0x7000d63c"; ["itemClass"] = 178; ["category"] = 12; }; -- Remmenaeg's Armour
  [1879103037] = { ["itemIdHex"] = "0x7000d63d"; ["itemClass"] = 178; ["category"] = 12; }; -- Ivar's Banner
  [1879103038] = { ["itemIdHex"] = "0x7000d63e"; ["itemClass"] = 178; ["category"] = 12; }; -- Naruhel's Dress
  [1879103039] = { ["itemIdHex"] = "0x7000d63f"; ["itemClass"] = 178; ["category"] = 12; }; -- Head of Bogbereth
  [1879103040] = { ["itemIdHex"] = "0x7000d640"; ["itemClass"] = 178; ["category"] = 12; }; -- Sambrog's Helm
  [1879103041] = { ["itemIdHex"] = "0x7000d641"; ["itemClass"] = 178; ["category"] = 12; }; -- The Mirror of Mordirith
  [1879103042] = { ["itemIdHex"] = "0x7000d642"; ["itemClass"] = 178; ["category"] = 12; }; -- Ferndur's Skull
  [1879103043] = { ["itemIdHex"] = "0x7000d643"; ["itemClass"] = 178; ["category"] = 12; }; -- The Skull of Thorog
  [1879103044] = { ["itemIdHex"] = "0x7000d644"; ["itemClass"] = 178; ["category"] = 12; }; -- Udunion's Swords
  [1879103045] = { ["itemIdHex"] = "0x7000d645"; ["itemClass"] = 178; ["category"] = 12; }; -- Tentacle of Helchgam
  [1879103078] = { ["itemIdHex"] = "0x7000d666"; ["itemClass"] = 178; ["category"] = 12; }; -- Thaurlach's Blade
  [1879103239] = { ["itemIdHex"] = "0x7000d707"; ["itemClass"] = 178; ["category"] = 13; }; -- Violet
  [1879103240] = { ["itemIdHex"] = "0x7000d708"; ["itemClass"] = 178; ["category"] = 13; }; -- White Honeysuckle
  [1879103241] = { ["itemIdHex"] = "0x7000d709"; ["itemClass"] = 178; ["category"] = 13; }; -- Primrose
  [1879103242] = { ["itemIdHex"] = "0x7000d70a"; ["itemClass"] = 178; ["category"] = 13; }; -- Marigold
  [1879109296] = { ["itemIdHex"] = "0x7000eeb0"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Tin Token
  [1879109297] = { ["itemIdHex"] = "0x7000eeb1"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Iron Token
  [1879109298] = { ["itemIdHex"] = "0x7000eeb2"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Silver Token
  [1879109299] = { ["itemIdHex"] = "0x7000eeb3"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Gold Token
  [1879109300] = { ["itemIdHex"] = "0x7000eeb4"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Platinum Token
  [1879109999] = { ["itemIdHex"] = "0x7000f16f"; ["itemClass"] = 102; ["category"] = 12; }; -- Cunning Catfish
  [1879110000] = { ["itemIdHex"] = "0x7000f170"; ["itemClass"] = 102; ["category"] = 12; }; -- Superb Smelt
  [1879110002] = { ["itemIdHex"] = "0x7000f172"; ["itemClass"] = 102; ["category"] = 12; }; -- Big Mouth Bass
  [1879110003] = { ["itemIdHex"] = "0x7000f173"; ["itemClass"] = 102; ["category"] = 12; }; -- Barbarous Barbel
  [1879110004] = { ["itemIdHex"] = "0x7000f174"; ["itemClass"] = 102; ["category"] = 12; }; -- Fantastic Flounder
  [1879110005] = { ["itemIdHex"] = "0x7000f175"; ["itemClass"] = 102; ["category"] = 12; }; -- Gleaming Grayling
  [1879110006] = { ["itemIdHex"] = "0x7000f176"; ["itemClass"] = 102; ["category"] = 12; }; -- Huge Houting
  [1879110007] = { ["itemIdHex"] = "0x7000f177"; ["itemClass"] = 102; ["category"] = 12; }; -- Nasty Nine-spined Stickleback
  [1879110008] = { ["itemIdHex"] = "0x7000f178"; ["itemClass"] = 102; ["category"] = 12; }; -- Colourful Charr
  [1879110009] = { ["itemIdHex"] = "0x7000f179"; ["itemClass"] = 102; ["category"] = 12; }; -- Brawny Bullhead
  [1879110010] = { ["itemIdHex"] = "0x7000f17a"; ["itemClass"] = 102; ["category"] = 12; }; -- Giant Goldfish
  [1879110011] = { ["itemIdHex"] = "0x7000f17b"; ["itemClass"] = 102; ["category"] = 12; }; -- Delightful Dace
  [1879110012] = { ["itemIdHex"] = "0x7000f17c"; ["itemClass"] = 102; ["category"] = 12; }; -- Great Golden Mullet
  [1879110013] = { ["itemIdHex"] = "0x7000f17d"; ["itemClass"] = 102; ["category"] = 12; }; -- Perfect Perch
  [1879110014] = { ["itemIdHex"] = "0x7000f17e"; ["itemClass"] = 102; ["category"] = 12; }; -- Magnificent Minnow
  [1879110015] = { ["itemIdHex"] = "0x7000f17f"; ["itemClass"] = 102; ["category"] = 12; }; -- Tricky Three-spined Stickleback
  [1879110016] = { ["itemIdHex"] = "0x7000f180"; ["itemClass"] = 102; ["category"] = 12; }; -- Ruthless Rudd
  [1879110017] = { ["itemIdHex"] = "0x7000f181"; ["itemClass"] = 102; ["category"] = 12; }; -- Perfect Pike
  [1879110018] = { ["itemIdHex"] = "0x7000f182"; ["itemClass"] = 102; ["category"] = 12; }; -- Bright Bitterling
  [1879110019] = { ["itemIdHex"] = "0x7000f183"; ["itemClass"] = 102; ["category"] = 12; }; -- Courageous Carp
  [1879110182] = { ["itemIdHex"] = "0x7000f226"; ["itemClass"] = 102; ["category"] = 12; }; -- 6-pound Salmon
  [1879110183] = { ["itemIdHex"] = "0x7000f227"; ["itemClass"] = 102; ["category"] = 12; }; -- 30-pound Salmon
  [1879110184] = { ["itemIdHex"] = "0x7000f228"; ["itemClass"] = 102; ["category"] = 12; }; -- 20-pound Salmon
  [1879110185] = { ["itemIdHex"] = "0x7000f229"; ["itemClass"] = 102; ["category"] = 12; }; -- 4-pound Salmon
  [1879110186] = { ["itemIdHex"] = "0x7000f22a"; ["itemClass"] = 102; ["category"] = 12; }; -- 10-pound Salmon
  [1879110187] = { ["itemIdHex"] = "0x7000f22b"; ["itemClass"] = 102; ["category"] = 12; }; -- 15-pound Salmon
  [1879110188] = { ["itemIdHex"] = "0x7000f22c"; ["itemClass"] = 27; ["category"] = 12; }; -- 50-pound Salmon
  [1879110189] = { ["itemIdHex"] = "0x7000f22d"; ["itemClass"] = 102; ["category"] = 12; }; -- 40-pound Salmon
  [1879110190] = { ["itemIdHex"] = "0x7000f22e"; ["itemClass"] = 102; ["category"] = 12; }; -- 2-pound Salmon
  [1879110285] = { ["itemIdHex"] = "0x7000f28d"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Tundra Bear Corpse
  [1879110286] = { ["itemIdHex"] = "0x7000f28e"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Winter-tusk Skull
  [1879110287] = { ["itemIdHex"] = "0x7000f28f"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Frost-antler Head
  [1879110288] = { ["itemIdHex"] = "0x7000f290"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Sabre-tooth Corpse
  [1879110289] = { ["itemIdHex"] = "0x7000f291"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Wolverine Corpse
  [1879110290] = { ["itemIdHex"] = "0x7000f292"; ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Winter-worm Corpse
  [1879112716] = { ["itemIdHex"] = "0x7000fc0c"; ["itemClass"] = 178; ["category"] = 10; }; -- Broken Signet
  [1879112717] = { ["itemIdHex"] = "0x7000fc0d"; ["itemClass"] = 178; ["category"] = 10; }; -- Vile Bronze Coin
  [1879112718] = { ["itemIdHex"] = "0x7000fc0e"; ["itemClass"] = 178; ["category"] = 10; }; -- Ring of Devotion
  [1879112719] = { ["itemIdHex"] = "0x7000fc0f"; ["itemClass"] = 178; ["category"] = 10; }; -- Banner of the Iron Crown
  [1879112720] = { ["itemIdHex"] = "0x7000fc10"; ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Triumph
  [1879112721] = { ["itemIdHex"] = "0x7000fc11"; ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Victory
  [1879112722] = { ["itemIdHex"] = "0x7000fc12"; ["itemClass"] = 178; ["category"] = 10; }; -- Emblem of the Oath Holder
  [1879115674] = { ["itemIdHex"] = "0x7001079a"; ["itemClass"] = 27; ["category"] = 8; }; -- Amberjack
  [1879115675] = { ["itemIdHex"] = "0x7001079b"; ["itemClass"] = 27; ["category"] = 8; }; -- Luillim
  [1879115676] = { ["itemIdHex"] = "0x7001079c"; ["itemClass"] = 27; ["category"] = 8; }; -- Drum
  [1879115678] = { ["itemIdHex"] = "0x7001079e"; ["itemClass"] = 178; ["category"] = 8; }; -- Celebhal
  [1879115679] = { ["itemIdHex"] = "0x7001079f"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Summer Festival Token
  [1879115708] = { ["itemIdHex"] = "0x700107bc"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Summerfest Race Token
  [1879115920] = { ["itemIdHex"] = "0x70010890"; ["itemClass"] = 178; ["category"] = 8; }; -- Medium Fish
  [1879115923] = { ["itemIdHex"] = "0x70010893"; ["itemClass"] = 178; ["category"] = 8; }; -- Large Fish
  [1879115924] = { ["itemIdHex"] = "0x70010894"; ["itemClass"] = 178; ["category"] = 8; }; -- Starry Flounder
  [1879115925] = { ["itemIdHex"] = "0x70010895"; ["itemClass"] = 178; ["category"] = 8; }; -- Silver Haddock
  [1879115927] = { ["itemIdHex"] = "0x70010897"; ["itemClass"] = 178; ["category"] = 8; }; -- Small Fish
  [1879115929] = { ["itemIdHex"] = "0x70010899"; ["itemClass"] = 178; ["category"] = 8; }; -- Golden Redfish
  [1879116031] = { ["itemIdHex"] = "0x700108ff"; ["itemClass"] = 178; ["category"] = 13; }; -- Man Mask Token
  [1879116035] = { ["itemIdHex"] = "0x70010903"; ["itemClass"] = 178; ["category"] = 13; }; -- Elf Mask Token
  [1879116039] = { ["itemIdHex"] = "0x70010907"; ["itemClass"] = 178; ["category"] = 13; }; -- Hobbit Mask Token
  [1879116043] = { ["itemIdHex"] = "0x7001090b"; ["itemClass"] = 178; ["category"] = 13; }; -- Dwarf Mask Token
  [1879124334] = { ["itemIdHex"] = "0x7001296e"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Thorog's Fang
  [1879124335] = { ["itemIdHex"] = "0x7001296f"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Thorog's Claw
  [1879124336] = { ["itemIdHex"] = "0x70012970"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Thorog's Horn
  [1879124337] = { ["itemIdHex"] = "0x70012971"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Scrap of Storvâgûn's Armour
  [1879124338] = { ["itemIdHex"] = "0x70012972"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Zaudru's Stinger
  [1879124339] = { ["itemIdHex"] = "0x70012973"; ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Amulet of the Witch-King
  [1879124340] = { ["itemIdHex"] = "0x70012974"; ["itemClass"] = 178; ["category"] = 10; }; -- Scrap of Wisdán's Cloak
  [1879124341] = { ["itemIdHex"] = "0x70012975"; ["itemClass"] = 178; ["category"] = 10; }; -- Breastplate of Gruglok
  [1879124342] = { ["itemIdHex"] = "0x70012976"; ["itemClass"] = 178; ["category"] = 10; }; -- Blade of Dúnachar
  [1879124343] = { ["itemIdHex"] = "0x70012977"; ["itemClass"] = 178; ["category"] = 10; }; -- Udúnion's Horn
  [1879124344] = { ["itemIdHex"] = "0x70012978"; ["itemClass"] = 178; ["category"] = 10; }; -- Cloven Helm of Lagmas
  [1879124345] = { ["itemIdHex"] = "0x70012979"; ["itemClass"] = 178; ["category"] = 10; }; -- Helchgam's Beak
  [1879124406] = { ["itemIdHex"] = "0x700129b6"; ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Triumph
  [1879124455] = { ["itemIdHex"] = "0x700129e7"; ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Rhunendin Victory
  [1879124456] = { ["itemIdHex"] = "0x700129e8"; ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Rammas Deluon Victory
  [1879124457] = { ["itemIdHex"] = "0x700129e9"; ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Aughaire Victory
  [1879125194] = { ["itemIdHex"] = "0x70012cca"; ["itemClass"] = 178; ["category"] = 10; }; -- Vile Silver Coin
  [1879135353] = { ["itemIdHex"] = "0x70015479"; ["itemClass"] = 178; ["category"] = 11; }; -- Hundi's Token
  [1879135973] = { ["itemIdHex"] = "0x700156e5"; ["itemClass"] = 178; ["category"] = 11; }; -- Snári's Token
  [1879138033] = { ["itemIdHex"] = "0x70015ef1"; ["itemClass"] = 178; ["category"] = 10; }; -- Writ of Angmar
  [1879138034] = { ["itemIdHex"] = "0x70015ef2"; ["itemClass"] = 178; ["category"] = 10; }; -- Writ of Annúminas
  [1879138035] = { ["itemIdHex"] = "0x70015ef3"; ["itemClass"] = 178; ["category"] = 10; }; -- Writ of Helegrod
  [1879143481] = { ["itemIdHex"] = "0x70017439"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Courage
  [1879143482] = { ["itemIdHex"] = "0x7001743a"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Courage
  [1879143483] = { ["itemIdHex"] = "0x7001743b"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Courage
  [1879143484] = { ["itemIdHex"] = "0x7001743c"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Silver Coin of Courage
  [1879143485] = { ["itemIdHex"] = "0x7001743d"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Silver Coin of Courage
  [1879143486] = { ["itemIdHex"] = "0x7001743e"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Silver Coin of Courage
  [1879143487] = { ["itemIdHex"] = "0x7001743f"; ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Courage
  [1879143500] = { ["itemIdHex"] = "0x7001744c"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Hand
  [1879143501] = { ["itemIdHex"] = "0x7001744d"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Resolve
  [1879143502] = { ["itemIdHex"] = "0x7001744e"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Strength
  [1879143503] = { ["itemIdHex"] = "0x7001744f"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Heart
  [1879143504] = { ["itemIdHex"] = "0x70017450"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Spirit
  [1879143505] = { ["itemIdHex"] = "0x70017451"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Hand
  [1879143506] = { ["itemIdHex"] = "0x70017452"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Resolve
  [1879143507] = { ["itemIdHex"] = "0x70017453"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Strength
  [1879143508] = { ["itemIdHex"] = "0x70017454"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Heart
  [1879143509] = { ["itemIdHex"] = "0x70017455"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Spirit
  [1879143510] = { ["itemIdHex"] = "0x70017456"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Hand
  [1879143511] = { ["itemIdHex"] = "0x70017457"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Resolve
  [1879143512] = { ["itemIdHex"] = "0x70017458"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Strength
  [1879143513] = { ["itemIdHex"] = "0x70017459"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Heart
  [1879143514] = { ["itemIdHex"] = "0x7001745a"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Spirit
  [1879143537] = { ["itemIdHex"] = "0x70017471"; ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Hand
  [1879143538] = { ["itemIdHex"] = "0x70017472"; ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Resolve
  [1879143539] = { ["itemIdHex"] = "0x70017473"; ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Strength
  [1879143540] = { ["itemIdHex"] = "0x70017474"; ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Heart
  [1879143541] = { ["itemIdHex"] = "0x70017475"; ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Spirit
  [1879143542] = { ["itemIdHex"] = "0x70017476"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Silver Coin of Hand
  [1879143543] = { ["itemIdHex"] = "0x70017477"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Silver Coin of Resolve
  [1879143544] = { ["itemIdHex"] = "0x70017478"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Silver Coin of Hand
  [1879143545] = { ["itemIdHex"] = "0x70017479"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Silver Coin of Resolve
  [1879143546] = { ["itemIdHex"] = "0x7001747a"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Silver Coin of Hand
  [1879143547] = { ["itemIdHex"] = "0x7001747b"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Silver Coin of Resolve
  [1879143548] = { ["itemIdHex"] = "0x7001747c"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Gold Coin of Strength
  [1879143549] = { ["itemIdHex"] = "0x7001747d"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Gold Coin of Heart
  [1879143550] = { ["itemIdHex"] = "0x7001747e"; ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Gold Coin of Spirit
  [1879143551] = { ["itemIdHex"] = "0x7001747f"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Gold Coin of Strength
  [1879143552] = { ["itemIdHex"] = "0x70017480"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Gold Coin of Heart
  [1879143553] = { ["itemIdHex"] = "0x70017481"; ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Gold Coin of Spirit
  [1879143554] = { ["itemIdHex"] = "0x70017482"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Gold Coin of Strength
  [1879143555] = { ["itemIdHex"] = "0x70017483"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Gold Coin of Heart
  [1879143556] = { ["itemIdHex"] = "0x70017484"; ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Gold Coin of Spirit
  [1879145158] = { ["itemIdHex"] = "0x70017ac6"; ["itemClass"] = 178; ["category"] = 11; }; -- Khuzdul Tablets
  [1879145168] = { ["itemIdHex"] = "0x70017ad0"; ["itemClass"] = 178; ["category"] = 11; }; -- Rusted Dwarf Tools
  [1879145790] = { ["itemIdHex"] = "0x70017d3e"; ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Tyrant's Crest
  [1879145791] = { ["itemIdHex"] = "0x70017d3f"; ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Chieftain's Brooch
  [1879145796] = { ["itemIdHex"] = "0x70017d44"; ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Brilliant Spirit Stone
  [1879147329] = { ["itemIdHex"] = "0x70018341"; ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Victory
  [1879147798] = { ["itemIdHex"] = "0x70018516"; ["itemClass"] = 178; ["category"] = 12; }; -- Kranklûk's Hammer
  [1879147799] = { ["itemIdHex"] = "0x70018517"; ["itemClass"] = 178; ["category"] = 12; }; -- Morhûn's Gemstone
  [1879147800] = { ["itemIdHex"] = "0x70018518"; ["itemClass"] = 178; ["category"] = 12; }; -- Fungal Mushroom
  [1879147801] = { ["itemIdHex"] = "0x70018519"; ["itemClass"] = 178; ["category"] = 12; }; -- Gurvand's Head
  [1879147802] = { ["itemIdHex"] = "0x7001851a"; ["itemClass"] = 178; ["category"] = 12; }; -- Stinger of Brúmbereth
  [1879147803] = { ["itemIdHex"] = "0x7001851b"; ["itemClass"] = 178; ["category"] = 12; }; -- Grimreaver
  [1879147804] = { ["itemIdHex"] = "0x7001851c"; ["itemClass"] = 178; ["category"] = 12; }; -- Egg of the Mistress
  [1879148394] = { ["itemIdHex"] = "0x7001876a"; ["itemClass"] = 178; ["category"] = 12; }; -- Shield of the White Hand
  [1879148395] = { ["itemIdHex"] = "0x7001876b"; ["itemClass"] = 178; ["category"] = 12; }; -- White Hand Helm and Feathers
  [1879148396] = { ["itemIdHex"] = "0x7001876c"; ["itemClass"] = 178; ["category"] = 12; }; -- Igash's Trinket
  [1879148397] = { ["itemIdHex"] = "0x7001876d"; ["itemClass"] = 178; ["category"] = 12; }; -- The Beast's Drum
  [1879148398] = { ["itemIdHex"] = "0x7001876e"; ["itemClass"] = 178; ["category"] = 12; }; -- Gothghaash's Symbol
  [1879148399] = { ["itemIdHex"] = "0x7001876f"; ["itemClass"] = 178; ["category"] = 12; }; -- Glothrok's Token
  [1879149147] = { ["itemIdHex"] = "0x70018a5b"; ["itemClass"] = 178; ["category"] = 10; }; -- Iron Coin of Knowledge
  [1879149148] = { ["itemIdHex"] = "0x70018a5c"; ["itemClass"] = 178; ["category"] = 10; }; -- Iron Coin of Fortitude
  [1879149371] = { ["itemIdHex"] = "0x70018b3b"; ["itemClass"] = 178; ["category"] = 12; }; -- General Talug's Armour
  [1879149481] = { ["itemIdHex"] = "0x70018ba9"; ["itemClass"] = 178; ["category"] = 12; }; -- Watcher's Token
  [1879149757] = { ["itemIdHex"] = "0x70018cbd"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Old Winter Festival Token
  [1879149799] = { ["itemIdHex"] = "0x70018ce7"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Yule Horse Race Token
  [1879150061] = { ["itemIdHex"] = "0x70018ded"; ["itemClass"] = 178; ["category"] = 14; }; -- Iron Garrison Resource Token
  [1879150131] = { ["itemIdHex"] = "0x70018e33"; ["itemClass"] = 178; ["category"] = 15; }; -- Lothlórien Gold Leaf
  [1879150132] = { ["itemIdHex"] = "0x70018e34"; ["itemClass"] = 178; ["category"] = 15; }; -- Lothlórien Silver Branch
  [1879151374] = { ["itemIdHex"] = "0x7001930e"; ["itemClass"] = 178; ["category"] = 8; }; -- Token of Salutation
  [1879151743] = { ["itemIdHex"] = "0x7001947f"; ["itemClass"] = 178; ["category"] = 13; }; -- Spring Leaf
  [1879151887] = { ["itemIdHex"] = "0x7001950f"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Hand
  [1879151888] = { ["itemIdHex"] = "0x70019510"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Courage
  [1879151889] = { ["itemIdHex"] = "0x70019511"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Spirit
  [1879151904] = { ["itemIdHex"] = "0x70019520"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Strength
  [1879151905] = { ["itemIdHex"] = "0x70019521"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Heart
  [1879151908] = { ["itemIdHex"] = "0x70019524"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Resolve
  [1879151992] = { ["itemIdHex"] = "0x70019578"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Glistening Elf-stone of Resolve
  [1879151996] = { ["itemIdHex"] = "0x7001957c"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Uncut Elf-stone of Strength
  [1879151999] = { ["itemIdHex"] = "0x7001957f"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Uncut Elf-stone of Hand
  [1879152000] = { ["itemIdHex"] = "0x70019580"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Glistening Elf-stone of Hand
  [1879152004] = { ["itemIdHex"] = "0x70019584"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Elf-stone of Hand
  [1879152011] = { ["itemIdHex"] = "0x7001958b"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Glistening Elf-stone of Strength
  [1879152017] = { ["itemIdHex"] = "0x70019591"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Uncut Elf-stone of Resolve
  [1879152023] = { ["itemIdHex"] = "0x70019597"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Elf-stone of Strength
  [1879152025] = { ["itemIdHex"] = "0x70019599"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Elf-stone of Resolve
  [1879155363] = { ["itemIdHex"] = "0x7001a2a3"; ["itemClass"] = 178; ["category"] = 11; }; -- Bright Emblem of Nimrodel
  [1879155768] = { ["itemIdHex"] = "0x7001a438"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Skirmish Mark
  [1879159674] = { ["itemIdHex"] = "0x7001b37a"; ["itemClass"] = 178; ["category"] = 12; }; -- Nornúan's Head
  [1879159675] = { ["itemIdHex"] = "0x7001b37b"; ["itemClass"] = 178; ["category"] = 12; }; -- Small Turtle Shell
  [1879160876] = { ["itemIdHex"] = "0x7001b82c"; ["itemClass"] = 178; ["category"] = 12; }; -- Thaguzg's Armour
  [1879160877] = { ["itemIdHex"] = "0x7001b82d"; ["itemClass"] = 178; ["category"] = 12; }; -- The Blind One's Skull
  [1879160878] = { ["itemIdHex"] = "0x7001b82e"; ["itemClass"] = 178; ["category"] = 12; }; -- Zholuga's Head
  [1879160879] = { ["itemIdHex"] = "0x7001b82f"; ["itemClass"] = 178; ["category"] = 12; }; -- Istûm's Head
  [1879160880] = { ["itemIdHex"] = "0x7001b830"; ["itemClass"] = 178; ["category"] = 12; }; -- Flâgît's Head
  [1879160881] = { ["itemIdHex"] = "0x7001b831"; ["itemClass"] = 178; ["category"] = 12; }; -- Ergoth's Wings
  [1879160882] = { ["itemIdHex"] = "0x7001b832"; ["itemClass"] = 178; ["category"] = 12; }; -- Caerlug's Arm
  [1879167037] = { ["itemIdHex"] = "0x7001d03d"; ["itemClass"] = 178; ["category"] = 14; }; -- Ceremonial Dwarf-axe
  [1879167038] = { ["itemIdHex"] = "0x7001d03e"; ["itemClass"] = 178; ["category"] = 14; }; -- Black-wood Bow
  [1879167039] = { ["itemIdHex"] = "0x7001d03f"; ["itemClass"] = 178; ["category"] = 14; }; -- 'Battle of Dagorlad' Tapestry
  [1879167040] = { ["itemIdHex"] = "0x7001d040"; ["itemClass"] = 178; ["category"] = 14; }; -- Record of Durin
  [1879167041] = { ["itemIdHex"] = "0x7001d041"; ["itemClass"] = 178; ["category"] = 14; }; -- Dragon-helm
  [1879167042] = { ["itemIdHex"] = "0x7001d042"; ["itemClass"] = 178; ["category"] = 14; }; -- Royal Crown
  [1879167043] = { ["itemIdHex"] = "0x7001d043"; ["itemClass"] = 178; ["category"] = 14; }; -- Record of the Elf-lords
  [1879167044] = { ["itemIdHex"] = "0x7001d044"; ["itemClass"] = 178; ["category"] = 14; }; -- Feast of Harvestmath
  [1879167045] = { ["itemIdHex"] = "0x7001d045"; ["itemClass"] = 178; ["category"] = 14; }; -- Númenórean Sceptre
  [1879167046] = { ["itemIdHex"] = "0x7001d046"; ["itemClass"] = 178; ["category"] = 14; }; -- Silver Basin
  [1879167047] = { ["itemIdHex"] = "0x7001d047"; ["itemClass"] = 178; ["category"] = 14; }; -- Feast of Lithe
  [1879167049] = { ["itemIdHex"] = "0x7001d049"; ["itemClass"] = 178; ["category"] = 14; }; -- Record of the Race of Man
  [1879167050] = { ["itemIdHex"] = "0x7001d04a"; ["itemClass"] = 178; ["category"] = 14; }; -- Feast of Ethuilwereth
  [1879167051] = { ["itemIdHex"] = "0x7001d04b"; ["itemClass"] = 178; ["category"] = 14; }; -- Red Arrow
  [1879167053] = { ["itemIdHex"] = "0x7001d04d"; ["itemClass"] = 178; ["category"] = 14; }; -- 'Battle of Five Armies' Tapestry
  [1879167054] = { ["itemIdHex"] = "0x7001d04e"; ["itemClass"] = 178; ["category"] = 14; }; -- Engraved Elf-blade
  [1879167055] = { ["itemIdHex"] = "0x7001d04f"; ["itemClass"] = 178; ["category"] = 14; }; -- Statue of Elendil
  [1879167058] = { ["itemIdHex"] = "0x7001d052"; ["itemClass"] = 178; ["category"] = 14; }; -- Dúnedain Star
  [1879167059] = { ["itemIdHex"] = "0x7001d053"; ["itemClass"] = 178; ["category"] = 14; }; -- Beryl Pendant
  [1879167060] = { ["itemIdHex"] = "0x7001d054"; ["itemClass"] = 178; ["category"] = 14; }; -- 'Siege of Barad-dûr' Tapestry
  [1879167062] = { ["itemIdHex"] = "0x7001d056"; ["itemClass"] = 178; ["category"] = 14; }; -- Royal Circlet
  [1879167627] = { ["itemIdHex"] = "0x7001d28b"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Medallion of Moria
  [1879167628] = { ["itemIdHex"] = "0x7001d28c"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Medallion of Lothlórien
  [1879167629] = { ["itemIdHex"] = "0x7001d28d"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; ["old"] = true; }; -- Medallion of Dol Guldur
  [1879172361] = { ["itemIdHex"] = "0x7001e509"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Spirit
  [1879172362] = { ["itemIdHex"] = "0x7001e50a"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Resolve
  [1879172363] = { ["itemIdHex"] = "0x7001e50b"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Heart
  [1879172364] = { ["itemIdHex"] = "0x7001e50c"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Hand
  [1879172365] = { ["itemIdHex"] = "0x7001e50d"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Courage
  [1879172366] = { ["itemIdHex"] = "0x7001e50e"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Strength
  [1879172834] = { ["itemIdHex"] = "0x7001e6e2"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Eglain Token
  [1879173003] = { ["itemIdHex"] = "0x7001e78b"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Springfest Race Token
  [1879174739] = { ["itemIdHex"] = "0x7001ee53"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Document of Mount Ownership
  [1879175320] = { ["itemIdHex"] = "0x7001f098"; ["itemClass"] = 178; ["category"] = 15; }; -- Malledhrim Gold Star Emblem
  [1879175321] = { ["itemIdHex"] = "0x7001f099"; ["itemClass"] = 178; ["category"] = 15; }; -- Malledhrim Bronze Feather
  [1879179430] = { ["itemIdHex"] = "0x700200a6"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran's First Mark
  [1879179431] = { ["itemIdHex"] = "0x700200a7"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- First Mark
  [1879179432] = { ["itemIdHex"] = "0x700200a8"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran's Second Mark
  [1879179433] = { ["itemIdHex"] = "0x700200a9"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Second Mark
  [1879179434] = { ["itemIdHex"] = "0x700200aa"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran's Third Mark
  [1879179435] = { ["itemIdHex"] = "0x700200ab"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Third Mark
  [1879179436] = { ["itemIdHex"] = "0x700200ac"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Recruit's Mark
  [1879179439] = { ["itemIdHex"] = "0x700200af"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Esquire's Mark
  [1879179440] = { ["itemIdHex"] = "0x700200b0"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Guardsman's Mark
  [1879180935] = { ["itemIdHex"] = "0x70020687"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Naillan Campaign Mark
  [1879180936] = { ["itemIdHex"] = "0x70020688"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Cannuilan Campaign Mark
  [1879180937] = { ["itemIdHex"] = "0x70020689"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Eruilan Campaign Mark
  [1879180938] = { ["itemIdHex"] = "0x7002068a"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Adlan Campaign Mark
  [1879180964] = { ["itemIdHex"] = "0x700206a4"; ["itemClass"] = 178; ["category"] = 12; }; -- Black Robes
  [1879181000] = { ["itemIdHex"] = "0x700206c8"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Footman's Mark
  [1879181001] = { ["itemIdHex"] = "0x700206c9"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran Guardsman's Mark
  [1879181002] = { ["itemIdHex"] = "0x700206ca"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran Esquire's Mark
  [1879181003] = { ["itemIdHex"] = "0x700206cb"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran Footman's Mark
  [1879181948] = { ["itemIdHex"] = "0x70020a7c"; ["itemClass"] = 178; ["category"] = 15; }; -- Silver Token of the Wilds
  [1879181950] = { ["itemIdHex"] = "0x70020a7e"; ["itemClass"] = 178; ["category"] = 15; }; -- Golden Token of the Wilds
  [1879183133] = { ["itemIdHex"] = "0x70020f1d"; ["itemClass"] = 178; ["category"] = 13; }; -- Badge of Dishonour
  [1879183648] = { ["itemIdHex"] = "0x70021120"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Lefnuilan Campaign Mark
  [1879185000] = { ["itemIdHex"] = "0x70021668"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Ancient Silver Token
  [1879185001] = { ["itemIdHex"] = "0x70021669"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Ancient Gold Token
  [1879185086] = { ["itemIdHex"] = "0x700216be"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Eregion Mark
  [1879185087] = { ["itemIdHex"] = "0x700216bf"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Annúminas Mark
  [1879185088] = { ["itemIdHex"] = "0x700216c0"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Helegrod Mark
  [1879185098] = { ["itemIdHex"] = "0x700216ca"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Superior Third Mark
  [1879185136] = { ["itemIdHex"] = "0x700216f0"; ["itemClass"] = 178; ["category"] = 13; }; -- Badge of Taste
  [1879185893] = { ["itemIdHex"] = "0x700219e5"; ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Remove Dread Tome
  [1879185909] = { ["itemIdHex"] = "0x700219f5"; ["itemClass"] = 173; ["category"] = 8; ["old"] = true; }; -- Revival Tome
  [1879186958] = { ["itemIdHex"] = "0x70021e0e"; ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Apprentice Ingredient Pack
  [1879186959] = { ["itemIdHex"] = "0x70021e0f"; ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Journeyman Ingredient Pack
  [1879186960] = { ["itemIdHex"] = "0x70021e10"; ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Artisan Ingredient Pack
  [1879186961] = { ["itemIdHex"] = "0x70021e11"; ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Master Ingredient Pack
  [1879186962] = { ["itemIdHex"] = "0x70021e12"; ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Supreme Ingredient Pack
  [1879186963] = { ["itemIdHex"] = "0x70021e13"; ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Expert Ingredient Pack
  [1879191713] = { ["itemIdHex"] = "0x700230a1"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Great Barrow Mark
  [1879197800] = { ["itemIdHex"] = "0x70024868"; ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Upgrade Task Limit (+1)
  [1879199409] = { ["itemIdHex"] = "0x70024eb1"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Frostbluff Coin
  [1879200577] = { ["itemIdHex"] = "0x70025341"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; ["old"] = true; }; -- Medallion of the North-men
  [1879200721] = { ["itemIdHex"] = "0x700253d1"; ["itemClass"] = 178; ["category"] = 13; }; -- Anniversary Token
  [1879201266] = { ["itemIdHex"] = "0x700255f2"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Anniversary Race Token
  [1879201840] = { ["itemIdHex"] = "0x70025830"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Boots Medallion
  [1879201845] = { ["itemIdHex"] = "0x70025835"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Helmet Medallion
  [1879201846] = { ["itemIdHex"] = "0x70025836"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Boots Medallion
  [1879201854] = { ["itemIdHex"] = "0x7002583e"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Shoulder-guards Medallion
  [1879201856] = { ["itemIdHex"] = "0x70025840"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Helmet Medallion
  [1879201858] = { ["itemIdHex"] = "0x70025842"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Breastplate Medallion
  [1879201860] = { ["itemIdHex"] = "0x70025844"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Leg-guards Medallion
  [1879201868] = { ["itemIdHex"] = "0x7002584c"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Leg-guards Medallion
  [1879201869] = { ["itemIdHex"] = "0x7002584d"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Gauntlets Medallion
  [1879201874] = { ["itemIdHex"] = "0x70025852"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Gauntlets Medallion
  [1879201875] = { ["itemIdHex"] = "0x70025853"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Shoulder-guards Medallion
  [1879201878] = { ["itemIdHex"] = "0x70025856"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Breastplate Medallion
  [1879201943] = { ["itemIdHex"] = "0x70025897"; ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Upgrade Task Limit (+1)
  [1879201944] = { ["itemIdHex"] = "0x70025898"; ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Upgrade Task Limit (+1)
  [1879201945] = { ["itemIdHex"] = "0x70025899"; ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Upgrade Task Limit (+1)
  [1879201946] = { ["itemIdHex"] = "0x7002589a"; ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Upgrade Task Limit (+1)
  [1879202375] = { ["itemIdHex"] = "0x70025a47"; ["itemClass"] = 178; ["category"] = 11; ["shared"] = true; }; -- Shard
  [1879205077] = { ["itemIdHex"] = "0x700264d5"; ["itemClass"] = 178; ["category"] = 10; }; -- Gloves Token
  [1879205082] = { ["itemIdHex"] = "0x700264da"; ["itemClass"] = 178; ["category"] = 10; }; -- Leg-guards Token
  [1879205083] = { ["itemIdHex"] = "0x700264db"; ["itemClass"] = 178; ["category"] = 10; }; -- Shoulders Token
  [1879205086] = { ["itemIdHex"] = "0x700264de"; ["itemClass"] = 178; ["category"] = 10; }; -- Helm Token
  [1879205088] = { ["itemIdHex"] = "0x700264e0"; ["itemClass"] = 178; ["category"] = 10; }; -- Breastplate Token
  [1879205098] = { ["itemIdHex"] = "0x700264ea"; ["itemClass"] = 178; ["category"] = 10; }; -- Boots Token
  [1879205437] = { ["itemIdHex"] = "0x7002663d"; ["itemClass"] = 178; ["category"] = 15; }; -- Bronze Arnorian Coin
  [1879205438] = { ["itemIdHex"] = "0x7002663e"; ["itemClass"] = 178; ["category"] = 15; }; -- Silver Arnorian Coin
  [1879206049] = { ["itemIdHex"] = "0x700268a1"; ["itemClass"] = 178; ["category"] = 13; }; -- Buried Treasure Token
  [1879206113] = { ["itemIdHex"] = "0x700268e1"; ["itemClass"] = 178; ["category"] = 12; }; -- Flaming Shadow
  [1879206114] = { ["itemIdHex"] = "0x700268e2"; ["itemClass"] = 178; ["category"] = 12; }; -- Red Sapped Huorn Limb
  [1879206115] = { ["itemIdHex"] = "0x700268e3"; ["itemClass"] = 178; ["category"] = 12; }; -- White Sapped Huorn Limb
  [1879206610] = { ["itemIdHex"] = "0x70026ad2"; ["itemClass"] = 178; ["category"] = 13; }; -- Token Fish
  [1879206611] = { ["itemIdHex"] = "0x70026ad3"; ["itemClass"] = 178; ["category"] = 13; }; -- Bad Fish
  [1879206612] = { ["itemIdHex"] = "0x70026ad4"; ["itemClass"] = 178; ["category"] = 13; }; -- Big Fish
  [1879206613] = { ["itemIdHex"] = "0x70026ad5"; ["itemClass"] = 178; ["category"] = 13; }; -- Puny Fish
  [1879206672] = { ["itemIdHex"] = "0x70026b10"; ["itemClass"] = 178; ["category"] = 13; }; -- Easy Fish
  [1879206673] = { ["itemIdHex"] = "0x70026b11"; ["itemClass"] = 178; ["category"] = 13; }; -- Simple Fish
  [1879206674] = { ["itemIdHex"] = "0x70026b12"; ["itemClass"] = 178; ["category"] = 13; }; -- Possible Fish
  [1879206675] = { ["itemIdHex"] = "0x70026b13"; ["itemClass"] = 178; ["category"] = 13; }; -- Tricky Fish
  [1879206676] = { ["itemIdHex"] = "0x70026b14"; ["itemClass"] = 178; ["category"] = 13; }; -- Unlikely Fish
  [1879206848] = { ["itemIdHex"] = "0x70026bc0"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Race Token
  [1879207368] = { ["itemIdHex"] = "0x70026dc8"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Enguilan Campaign Mark
  [1879207894] = { ["itemIdHex"] = "0x70026fd6"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Halls of Night Mark
  [1879207904] = { ["itemIdHex"] = "0x70026fe0"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Inn of the Forsaken Mark
  [1879209189] = { ["itemIdHex"] = "0x700274e5"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Odothuilan Campaign Mark
  [1879217575] = { ["itemIdHex"] = "0x700295a7"; ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Westfold Ingredient Pack
  [1879218744] = { ["itemIdHex"] = "0x70029a38"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran's Fourth Mark
  [1879218745] = { ["itemIdHex"] = "0x70029a39"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Superior Fourth Mark
  [1879218746] = { ["itemIdHex"] = "0x70029a3a"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Fourth Mark
  [1879218928] = { ["itemIdHex"] = "0x70029af0"; ["itemClass"] = 178; ["category"] = 10; }; -- Scorched Shoulder-guard Token
  [1879218942] = { ["itemIdHex"] = "0x70029afe"; ["itemClass"] = 178; ["category"] = 10; }; -- Scorched Helm Token
  [1879221222] = { ["itemIdHex"] = "0x7002a3e6"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran Sergeant-at-Arms Mark
  [1879221259] = { ["itemIdHex"] = "0x7002a40b"; ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Sergeant-at-Arms Mark
  [1879222280] = { ["itemIdHex"] = "0x7002a808"; ["itemClass"] = 178; ["category"] = 12; }; -- Phial of Eternal Flame
  [1879222281] = { ["itemIdHex"] = "0x7002a809"; ["itemClass"] = 178; ["category"] = 12; }; -- Battered Scale
  [1879223715] = { ["itemIdHex"] = "0x7002ada3"; ["itemClass"] = 178; ["category"] = 13; }; -- Farmers Faire Token
  [1879224343] = { ["itemIdHex"] = "0x7002b017"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Mark
  [1879224344] = { ["itemIdHex"] = "0x7002b018"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Medallion
  [1879224345] = { ["itemIdHex"] = "0x7002b019"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Seal
  [1879226347] = { ["itemIdHex"] = "0x7002b7eb"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Orthanc Sigil-fragment
  [1879227344] = { ["itemIdHex"] = "0x7002bbd0"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Farmers Faire Race Token
  [1879227924] = { ["itemIdHex"] = "0x7002be14"; ["itemClass"] = 178; ["category"] = 12; }; -- Orrery-fragment
  [1879227925] = { ["itemIdHex"] = "0x7002be15"; ["itemClass"] = 178; ["category"] = 12; }; -- Chipped Throne-fragment
  [1879227926] = { ["itemIdHex"] = "0x7002be16"; ["itemClass"] = 178; ["category"] = 12; }; -- Shattered Ring-fragment
  [1879229676] = { ["itemIdHex"] = "0x7002c4ec"; ["itemClass"] = 178; ["category"] = 15; }; -- Golden Token of the Anduin
  [1879229677] = { ["itemIdHex"] = "0x7002c4ed"; ["itemClass"] = 178; ["category"] = 15; }; -- Silver Token of the Anduin
  [1879229829] = { ["itemIdHex"] = "0x7002c585"; ["itemClass"] = 178; ["category"] = 14; }; -- Grand Feast of Ethuilwereth
  [1879229830] = { ["itemIdHex"] = "0x7002c586"; ["itemClass"] = 178; ["category"] = 14; }; -- Grand Feast of Lithe
  [1879229832] = { ["itemIdHex"] = "0x7002c588"; ["itemClass"] = 178; ["category"] = 14; }; -- Elaborate Dúnedain Star
  [1879229833] = { ["itemIdHex"] = "0x7002c589"; ["itemClass"] = 178; ["category"] = 14; }; -- Elaborate Royal Circlet
  [1879229835] = { ["itemIdHex"] = "0x7002c58b"; ["itemClass"] = 178; ["category"] = 14; }; -- Adorned Royal Crown
  [1879229836] = { ["itemIdHex"] = "0x7002c58c"; ["itemClass"] = 178; ["category"] = 14; }; -- Adorned Dragon-helm
  [1879229838] = { ["itemIdHex"] = "0x7002c58e"; ["itemClass"] = 178; ["category"] = 14; }; -- Illuminated Record of the Race of Man
  [1879229839] = { ["itemIdHex"] = "0x7002c58f"; ["itemClass"] = 178; ["category"] = 14; }; -- Illuminated Record of the Elf-lords
  [1879229841] = { ["itemIdHex"] = "0x7002c591"; ["itemClass"] = 178; ["category"] = 14; }; -- Embroidered 'Battle of Five Armies' Tapestry
  [1879229842] = { ["itemIdHex"] = "0x7002c592"; ["itemClass"] = 178; ["category"] = 14; }; -- Embroidered 'Battle of Dagorlad' Tapestry
  [1879229844] = { ["itemIdHex"] = "0x7002c594"; ["itemClass"] = 178; ["category"] = 14; }; -- Flawless Ceremonial Dwarf-axe
  [1879229845] = { ["itemIdHex"] = "0x7002c595"; ["itemClass"] = 178; ["category"] = 14; }; -- Flawless Númenórean Sceptre
  [1879229847] = { ["itemIdHex"] = "0x7002c597"; ["itemClass"] = 178; ["category"] = 14; }; -- Engraved Red Arrow
  [1879229848] = { ["itemIdHex"] = "0x7002c598"; ["itemClass"] = 178; ["category"] = 14; }; -- Engraved Statue of Elendil
  [1879230183] = { ["itemIdHex"] = "0x7002c6e7"; ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Commendation
  [1879232299] = { ["itemIdHex"] = "0x7002cf2b"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Unhatched Spider Egg
  [1879233822] = { ["itemIdHex"] = "0x7002d51e"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Honorary Postman's Badge
  [1879234223] = { ["itemIdHex"] = "0x7002d6af"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Calenard Token
  [1879234649] = { ["itemIdHex"] = "0x7002d859"; ["itemClass"] = 178; ["category"] = 13; }; -- Sigil of Dedication
  [1879237261] = { ["itemIdHex"] = "0x7002e28d"; ["itemClass"] = 178; ["category"] = 15; }; -- Silver Token of the Riddermark
  [1879237278] = { ["itemIdHex"] = "0x7002e29e"; ["itemClass"] = 178; ["category"] = 15; }; -- Golden Token of the Riddermark
  [1879237349] = { ["itemIdHex"] = "0x7002e2e5"; ["itemClass"] = 27; ["category"] = 15; }; -- Token of Hytbold
  [1879238505] = { ["itemIdHex"] = "0x7002e769"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Festival Ticket
  [1879245065] = { ["itemIdHex"] = "0x70030109"; ["itemClass"] = 178; ["category"] = 14; }; -- Token of Effort
  [1879245827] = { ["itemIdHex"] = "0x70030403"; ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Eastemnet Ingredient Pack
  [1879251305] = { ["itemIdHex"] = "0x70031969"; ["itemClass"] = 178; ["category"] = 14; }; -- Red Ring
  [1879251306] = { ["itemIdHex"] = "0x7003196a"; ["itemClass"] = 178; ["category"] = 14; }; -- Feast of Cormarë
  [1879251307] = { ["itemIdHex"] = "0x7003196b"; ["itemClass"] = 178; ["category"] = 14; }; -- Flawless Annúminas Sceptre
  [1879251308] = { ["itemIdHex"] = "0x7003196c"; ["itemClass"] = 178; ["category"] = 14; }; -- Horn of Helm Hammerhand
  [1879251309] = { ["itemIdHex"] = "0x7003196d"; ["itemClass"] = 178; ["category"] = 14; }; -- Embroidered 'Battle of the Hornburg' Tapestry
  [1879251310] = { ["itemIdHex"] = "0x7003196e"; ["itemClass"] = 178; ["category"] = 14; }; -- Grand Feast of Cormarë
  [1879251311] = { ["itemIdHex"] = "0x7003196f"; ["itemClass"] = 178; ["category"] = 14; }; -- Illuminated Scroll of Kings
  [1879251312] = { ["itemIdHex"] = "0x70031970"; ["itemClass"] = 178; ["category"] = 14; }; -- Gondorian Crown
  [1879251313] = { ["itemIdHex"] = "0x70031971"; ["itemClass"] = 178; ["category"] = 14; }; -- Engraved Horn of Helm Hammerhand
  [1879251314] = { ["itemIdHex"] = "0x70031972"; ["itemClass"] = 178; ["category"] = 14; }; -- Scroll of Kings
  [1879251315] = { ["itemIdHex"] = "0x70031973"; ["itemClass"] = 178; ["category"] = 14; }; -- Annúminas Sceptre
  [1879251316] = { ["itemIdHex"] = "0x70031974"; ["itemClass"] = 178; ["category"] = 14; }; -- 'Battle of the Hornburg' Tapestry
  [1879251317] = { ["itemIdHex"] = "0x70031975"; ["itemClass"] = 178; ["category"] = 14; }; -- Adorned Gondorian Crown
  [1879251318] = { ["itemIdHex"] = "0x70031976"; ["itemClass"] = 178; ["category"] = 14; }; -- Elaborate Red Ring
  [1879255991] = { ["itemIdHex"] = "0x70032bb7"; ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; }; -- Mithril Coin
  [1879256449] = { ["itemIdHex"] = "0x70032d81"; ["itemClass"] = 27; ["category"] = 13; }; -- Yule Festival Token
  [1879257572] = { ["itemIdHex"] = "0x700331e4"; ["itemClass"] = 178; ["category"] = 13; }; -- Golden Festival Token
  [1879257626] = { ["itemIdHex"] = "0x7003321a"; ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Traveller's Writ
  [1879257627] = { ["itemIdHex"] = "0x7003321b"; ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Stable-master's Writ
  [1879259420] = { ["itemIdHex"] = "0x7003391c"; ["itemClass"] = 178; ["category"] = 15; }; -- Wildermore Coin
  [1879259421] = { ["itemIdHex"] = "0x7003391d"; ["itemClass"] = 178; ["category"] = 15; }; -- Gold Token of Wildermore
  [1879261930] = { ["itemIdHex"] = "0x700342ea"; ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Riddermark Token
  [1879269887] = { ["itemIdHex"] = "0x700361ff"; ["itemClass"] = 178; ["category"] = 15; }; -- Warband Token of Wildermore
  [1879271112] = { ["itemIdHex"] = "0x700366c8"; ["itemClass"] = 178; ["category"] = 15; }; -- Westemnet Iron Coin
  [1879277247] = { ["itemIdHex"] = "0x70037ebf"; ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; }; -- Universal Ingredient Pack
  [1879277688] = { ["itemIdHex"] = "0x70038078"; ["itemClass"] = 178; ["category"] = 14; }; -- 'Battle of the Field of Celebrant' Tapestry
  [1879277689] = { ["itemIdHex"] = "0x70038079"; ["itemClass"] = 178; ["category"] = 14; }; -- Horn of the Mark
  [1879277690] = { ["itemIdHex"] = "0x7003807a"; ["itemClass"] = 178; ["category"] = 14; }; -- Embroidered 'Battle of the Field of Celebrant' Tapestry
  [1879277691] = { ["itemIdHex"] = "0x7003807b"; ["itemClass"] = 178; ["category"] = 14; }; -- Grand Feast of Yáviérë
  [1879277692] = { ["itemIdHex"] = "0x7003807c"; ["itemClass"] = 178; ["category"] = 14; }; -- Necklace of Emeralds
  [1879277693] = { ["itemIdHex"] = "0x7003807d"; ["itemClass"] = 178; ["category"] = 14; }; -- Black Key
  [1879277694] = { ["itemIdHex"] = "0x7003807e"; ["itemClass"] = 178; ["category"] = 14; }; -- Adorned Black Key
  [1879277695] = { ["itemIdHex"] = "0x7003807f"; ["itemClass"] = 178; ["category"] = 14; }; -- Chronicle of Cirion and Eorl
  [1879277696] = { ["itemIdHex"] = "0x70038080"; ["itemClass"] = 178; ["category"] = 14; }; -- Illuminated Chronicle of Cirion and Eorl
  [1879277697] = { ["itemIdHex"] = "0x70038081"; ["itemClass"] = 178; ["category"] = 14; }; -- Fierce Sword
  [1879277698] = { ["itemIdHex"] = "0x70038082"; ["itemClass"] = 178; ["category"] = 14; }; -- Flawless Fierce Sword
  [1879277699] = { ["itemIdHex"] = "0x70038083"; ["itemClass"] = 178; ["category"] = 14; }; -- Engraved Horn of the Mark
  [1879277700] = { ["itemIdHex"] = "0x70038084"; ["itemClass"] = 178; ["category"] = 14; }; -- Elaborate Necklace of Emeralds
  [1879277701] = { ["itemIdHex"] = "0x70038085"; ["itemClass"] = 178; ["category"] = 14; }; -- Feast of Yáviérë
  [1879278927] = { ["itemIdHex"] = "0x7003854f"; ["itemClass"] = 27; ["category"] = 13; ["shared"] = true; ["old"] = true; }; -- Bounder's Token
  [1879302681] = { ["itemIdHex"] = "0x7003e219"; ["itemClass"] = 178; ["category"] = 14; }; -- Receipt of Armament Exchange
  [1879303013] = { ["itemIdHex"] = "0x7003e365"; ["itemClass"] = 178; ["category"] = 15; }; -- Fangorn Leaf
  [1879303343] = { ["itemIdHex"] = "0x7003e4af"; ["itemClass"] = 178; ["category"] = 8; }; -- Steel Token
  [1879306057] = { ["itemIdHex"] = "0x7003ef49"; ["itemClass"] = 178; ["category"] = 15; }; -- Amroth Silver Piece
  [1879306058] = { ["itemIdHex"] = "0x7003ef4a"; ["itemClass"] = 178; ["category"] = 15; }; -- East Gondor Silver Piece
  [1879314933] = { ["itemIdHex"] = "0x700411f5"; ["itemClass"] = 178; ["category"] = 15; }; -- Central Gondor Silver Piece
  [1879318665] = { ["itemIdHex"] = "0x70042089"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Star of Merit
  [1879320706] = { ["itemIdHex"] = "0x70042882"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Gift-giver's Brand
  [1879321808] = { ["itemIdHex"] = "0x70042cd0"; ["itemClass"] = 178; ["category"] = 15; }; -- Bingo Badge
  [1879324717] = { ["itemIdHex"] = "0x7004382d"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Morgul Crest
  [1879325632] = { ["itemIdHex"] = "0x70043bc0"; ["itemClass"] = 178; ["category"] = 15; }; -- Rhosgobel Oak Leaf
  [1879325664] = { ["itemIdHex"] = "0x70043be0"; ["itemClass"] = 178; ["category"] = 11; ["shared"] = true; }; -- Legendary Item XP Rune
  [1879326936] = { ["itemIdHex"] = "0x700440d8"; ["itemClass"] = 178; ["category"] = 15; }; -- Minas Tirith - Smiths' Token
  [1879326937] = { ["itemIdHex"] = "0x700440d9"; ["itemClass"] = 178; ["category"] = 15; }; -- Minas Tirith Silver Piece
  [1879326944] = { ["itemIdHex"] = "0x700440e0"; ["itemClass"] = 178; ["category"] = 15; }; -- Minas Tirith - Builders' Token
  [1879329799] = { ["itemIdHex"] = "0x70044c07"; ["itemClass"] = 178; ["category"] = 15; }; -- Minas Tirith - Burgsmen's Token
  [1879332436] = { ["itemIdHex"] = "0x70045654"; ["itemClass"] = 178; ["category"] = 10; }; -- Long-lost Coin
  [1879333869] = { ["itemIdHex"] = "0x70045bed"; ["itemClass"] = 27; ["category"] = 15; }; -- Host of the West Silver Piece
  [1879335251] = { ["itemIdHex"] = "0x70046153"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Helmet of the Pelennor Fields
  [1879335252] = { ["itemIdHex"] = "0x70046154"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Gauntlets of the Pelennor Fields
  [1879335253] = { ["itemIdHex"] = "0x70046155"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Bracelet of the Pelennor Fields
  [1879335254] = { ["itemIdHex"] = "0x70046156"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Tarnished Ring of the Pelennor Fields
  [1879335255] = { ["itemIdHex"] = "0x70046157"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Reclaimed Pelennor Defender's Gear
  [1879335256] = { ["itemIdHex"] = "0x70046158"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Earring of the Pelennor Fields
  [1879335257] = { ["itemIdHex"] = "0x70046159"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Leg-guards of the Pelennor Fields
  [1879335258] = { ["itemIdHex"] = "0x7004615a"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Shoulders of the Pelennor Fields
  [1879335259] = { ["itemIdHex"] = "0x7004615b"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Cracked Pocket-mirror
  [1879335260] = { ["itemIdHex"] = "0x7004615c"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Tarnished Necklace of the Pelennor Fields
  [1879335261] = { ["itemIdHex"] = "0x7004615d"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Boots of the Pelennor Fields
  [1879335262] = { ["itemIdHex"] = "0x7004615e"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Helmet of the Pelennor Fields
  [1879335263] = { ["itemIdHex"] = "0x7004615f"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Leg-guards of the Pelennor Fields
  [1879335264] = { ["itemIdHex"] = "0x70046160"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Tarnished Bracelet of the Pelennor Fields
  [1879335265] = { ["itemIdHex"] = "0x70046161"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Battle-damaged Equipment of the Pelennor Fields
  [1879335266] = { ["itemIdHex"] = "0x70046162"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Boots of the Pelennor Fields
  [1879335267] = { ["itemIdHex"] = "0x70046163"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Necklace of the Pelennor Fields
  [1879335268] = { ["itemIdHex"] = "0x70046164"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Chestplate of the Pelennor Fields
  [1879335269] = { ["itemIdHex"] = "0x70046165"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Tarnished Earring of the Pelennor Fields
  [1879335270] = { ["itemIdHex"] = "0x70046166"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Ring of the Pelennor Fields
  [1879335271] = { ["itemIdHex"] = "0x70046167"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Star-laden Tapestry
  [1879335272] = { ["itemIdHex"] = "0x70046168"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Ancient Ithil-coin
  [1879335273] = { ["itemIdHex"] = "0x70046169"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Gauntlets of the Pelennor Fields
  [1879335274] = { ["itemIdHex"] = "0x7004616a"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Chestplate of the Pelennor Fields
  [1879335275] = { ["itemIdHex"] = "0x7004616b"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Shoulders of the Pelennor Fields
  [1879338037] = { ["itemIdHex"] = "0x70046c35"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Crimson Extract
  [1879338038] = { ["itemIdHex"] = "0x70046c36"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Umber Extract
  [1879338039] = { ["itemIdHex"] = "0x70046c37"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Golden Extract
  [1879338040] = { ["itemIdHex"] = "0x70046c38"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Amber Extract
  [1879338041] = { ["itemIdHex"] = "0x70046c39"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Verdant Extract
  [1879338042] = { ["itemIdHex"] = "0x70046c3a"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Sapphire Extract
  [1879338043] = { ["itemIdHex"] = "0x70046c3b"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Violet Extract
  [1879340090] = { ["itemIdHex"] = "0x7004743a"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Officer's Bracelet of the Pelennor Fields
  [1879341063] = { ["itemIdHex"] = "0x70047807"; ["itemClass"] = 178; ["category"] = 15; }; -- Ithilien Essence Fragment
  [1879341064] = { ["itemIdHex"] = "0x70047808"; ["itemClass"] = 178; ["category"] = 8; }; -- Ithilien Scrap of an Essence Reclamation Scroll
  [1879343050] = { ["itemIdHex"] = "0x70047fca"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Tarnished Sigil of Gondor
  [1879345122] = { ["itemIdHex"] = "0x700487e2"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Gold Signet of the Thandrim
  [1879345125] = { ["itemIdHex"] = "0x700487e5"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Silver Signet of the Thandrim
  [1879352247] = { ["itemIdHex"] = "0x7004a3b7"; ["itemClass"] = 27; ["category"] = 6; ["shared"] = true; }; -- Motes of Enchantment
  [1879353887] = { ["itemIdHex"] = "0x7004aa1f"; ["itemClass"] = 178; ["category"] = 15; }; -- Token of Service
  [1879361622] = { ["itemIdHex"] = "0x7004c856"; ["itemClass"] = 178; ["category"] = 8; }; -- Sliver of Black Steel
  [1879361902] = { ["itemIdHex"] = "0x7004c96e"; ["itemClass"] = 178; ["category"] = 13; }; -- Scrap of an Essence Reclamation Scroll
  [1879362402] = { ["itemIdHex"] = "0x7004cb62"; ["itemClass"] = 178; ["category"] = 15; }; -- Token of the Lake and Rivers
  [1879364886] = { ["itemIdHex"] = "0x7004d516"; ["itemClass"] = 178; ["category"] = 13; }; -- Fragment of a Shadow Essence
  [1879368412] = { ["itemIdHex"] = "0x7004e2dc"; ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Rare Vanguard Relic Exchange Token
  [1879368413] = { ["itemIdHex"] = "0x7004e2dd"; ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Grand Abyssal Relic Exchange Token
  [1879368414] = { ["itemIdHex"] = "0x7004e2de"; ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Incomparable Vangard Relic Exchange Token
  [1879368415] = { ["itemIdHex"] = "0x7004e2df"; ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Abyssal Relic Exchange Token
  [1879368416] = { ["itemIdHex"] = "0x7004e2e0"; ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Greater Abyssal Relic Exchange Token
  [1879368479] = { ["itemIdHex"] = "0x7004e31f"; ["itemClass"] = 27; ["category"] = 15; }; -- Mark of the Longbeards
  [1879368818] = { ["itemIdHex"] = "0x7004e472"; ["itemClass"] = 178; ["category"] = 10; }; -- Festivity Token
  [1879369175] = { ["itemIdHex"] = "0x7004e5d7"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Thrâng's Vault Token
  [1879369423] = { ["itemIdHex"] = "0x7004e6cf"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Newfound Coin
  [1879377205] = { ["itemIdHex"] = "0x70050535"; ["itemClass"] = 178; ["category"] = 6; ["shared"] = true; }; -- Embers of Enchantment
  [1879378796] = { ["itemIdHex"] = "0x70050b6c"; ["itemClass"] = 178; ["category"] = 10; }; -- Coin of Grárik
  [1879381191] = { ["itemIdHex"] = "0x700514c7"; ["itemClass"] = 178; ["category"] = 6; ["shared"] = true; }; -- Figments of Splendour
  [1879383301] = { ["itemIdHex"] = "0x70051d05"; ["itemClass"] = 178; ["category"] = 8; }; -- Legendary Coin of Angmar
  [1879383302] = { ["itemIdHex"] = "0x70051d06"; ["itemClass"] = 178; ["category"] = 15; }; -- Himbar Token of Exchange
  [1879385805] = { ["itemIdHex"] = "0x700526cd"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Token of Ill Omens
  [1879385997] = { ["itemIdHex"] = "0x7005278d"; ["itemClass"] = 27; ["category"] = 15; }; -- Gúlmark
  [1879386515] = { ["itemIdHex"] = "0x70052993"; ["itemClass"] = 178; ["category"] = 15; }; -- Vales - Beorning Token
  [1879386518] = { ["itemIdHex"] = "0x70052996"; ["itemClass"] = 178; ["category"] = 15; }; -- Vales - Elf Token
  [1879386519] = { ["itemIdHex"] = "0x70052997"; ["itemClass"] = 178; ["category"] = 15; }; -- Vales - Woodmen Token
  [1879387494] = { ["itemIdHex"] = "0x70052d66"; ["itemClass"] = 178; ["category"] = 8; }; -- Legendary Coin of Moria
  [1879389108] = { ["itemIdHex"] = "0x700533b4"; ["itemClass"] = 178; ["category"] = 8; }; -- Legendary Coin of Mirkwood
  [1879389826] = { ["itemIdHex"] = "0x70053682"; ["itemClass"] = 27; ["category"] = 15; ["shared"] = true; }; -- Sigil of Imlad Ithil
  [1879401397] = { ["itemIdHex"] = "0x700563b5"; ["itemClass"] = 178; ["category"] = 10; }; -- Coin of the Bugan
  [1879403799] = { ["itemIdHex"] = "0x70056d17"; ["itemClass"] = 178; ["category"] = 15; }; -- Northern Gúlmark
  [1879406105] = { ["itemIdHex"] = "0x70057619"; ["itemClass"] = 178; ["category"] = 13; }; -- Midsummer Token
  [1879406458] = { ["itemIdHex"] = "0x7005777a"; ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Pet Harness
  [1879406459] = { ["itemIdHex"] = "0x7005777b"; ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Steed Halter
  [1879407802] = { ["itemIdHex"] = "0x70057cba"; ["itemClass"] = 27; ["category"] = 15; }; -- Copper Coin of Gundabad
  [1879410524] = { ["itemIdHex"] = "0x7005875c"; ["itemClass"] = 27; ["category"] = 14; ["shared"] = true; }; -- Elderslade Supply Pack
  [1879411090] = { ["itemIdHex"] = "0x70058992"; ["itemClass"] = 178; ["category"] = 15; }; -- Gabil'akkâ War-mark
  [1879413176] = { ["itemIdHex"] = "0x700591b8"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Mark of the Wilds
  [1879413185] = { ["itemIdHex"] = "0x700591c1"; ["itemClass"] = 178; ["category"] = 15; }; -- Bree-land Wood-mark
  [1879413574] = { ["itemIdHex"] = "0x70059346"; ["itemClass"] = 178; ["category"] = 15; }; -- Zakaf-beshek
  [1879416775] = { ["itemIdHex"] = "0x70059fc7"; ["itemClass"] = 178; ["category"] = 15; }; -- Gundabad Mountain-mark
  [1879416776] = { ["itemIdHex"] = "0x70059fc8"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Geode - Agate
  [1879416778] = { ["itemIdHex"] = "0x70059fca"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Geode - Amethyst
  [1879416779] = { ["itemIdHex"] = "0x70059fcb"; ["itemClass"] = 27; ["category"] = 15; }; -- Silver Coin of Gundabad
  [1879416781] = { ["itemIdHex"] = "0x70059fcd"; ["itemClass"] = 178; ["category"] = 15; }; -- Token of the Zhélruka
  [1879416782] = { ["itemIdHex"] = "0x70059fce"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Geode - Quartz
  [1879416787] = { ["itemIdHex"] = "0x70059fd3"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Geode - Gypsum
  [1879416791] = { ["itemIdHex"] = "0x70059fd7"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Geode - Jasper
  [1879416834] = { ["itemIdHex"] = "0x7005a002"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Token of Resolution
  [1879418432] = { ["itemIdHex"] = "0x7005a640"; ["itemClass"] = 178; ["category"] = 15; }; -- Token of the Kharum-ubnâr
  [1879418577] = { ["itemIdHex"] = "0x7005a6d1"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Token of Further Adventure
  [1879424263] = { ["itemIdHex"] = "0x7005bd07"; ["itemClass"] = 178; ["category"] = 11; ["shared"] = true; }; -- Ancient Script
  [1879442894] = { ["itemIdHex"] = "0x700605ce"; ["itemClass"] = 27; ["category"] = 15; }; -- Copper Bounder's Coin
  [1879443289] = { ["itemIdHex"] = "0x70060759"; ["itemClass"] = 178; ["category"] = 15; }; -- Mark of the Angle
  [1879448448] = { ["itemIdHex"] = "0x70061b80"; ["itemClass"] = 178; ["category"] = 15; }; -- Iron Coin of Cardolan
  [1879452571] = { ["itemIdHex"] = "0x70062b9b"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Delving Writ
  [1879454476] = { ["itemIdHex"] = "0x7006330c"; ["itemClass"] = 178; ["category"] = 15; }; -- Greyflood Mark
  [1879457091] = { ["itemIdHex"] = "0x70063d43"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Sárskillin
  [1879461938] = { ["itemIdHex"] = "0x70065032"; ["itemClass"] = 178; ["category"] = 15; }; -- Mark of Renewal
  [1879463586] = { ["itemIdHex"] = "0x700656a2"; ["itemClass"] = 27; ["category"] = 15; ["shared"] = true; }; -- Token of Heroism
  [1879464288] = { ["itemIdHex"] = "0x70065960"; ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Hero's Mark
  [1879465763] = { ["itemIdHex"] = "0x70065f23"; ["itemClass"] = 178; ["category"] = 14; ["shared"] = true; }; -- Participation Ribbon
  [1879465764] = { ["itemIdHex"] = "0x70065f24"; ["itemClass"] = 178; ["category"] = 14; ["shared"] = true; }; -- Runner-up Ribbon
  [1879465765] = { ["itemIdHex"] = "0x70065f25"; ["itemClass"] = 178; ["category"] = 14; ["shared"] = true; }; -- Winner Ribbon
  [1879465779] = { ["itemIdHex"] = "0x70065f33"; ["itemClass"] = 178; ["category"] = 15; }; -- Umbari Tâm
  [1879467015] = { ["itemIdHex"] = "0x70066407"; ["itemClass"] = 178; ["category"] = 14; ["shared"] = true; }; -- Luck-stone
  [1879473346] = { ["itemIdHex"] = "0x70067cc2"; ["itemClass"] = 178; ["category"] = 15; }; -- Eagle Bit
  [1879473347] = { ["itemIdHex"] = "0x70067cc3"; ["itemClass"] = 178; ["category"] = 15; }; -- Ledger-keeper Mark
  [1879479402] = { ["itemIdHex"] = "0x7006946a"; ["itemClass"] = 178; ["category"] = 14; ["shared"] = true; }; -- Umbar Craft Guild Mark
  [1879482783] = { ["itemIdHex"] = "0x7006a19f"; ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Menacing Tentacle
};

_G.WalletUsedCategories = {
  [1] = 9; -- Coin
  [2] = 13; -- Festivals and Events
  [3] = 15; -- Landscape
  [4] = 12; -- Taxidermy
  [5] = 8; -- Other
  [6] = 10; -- Instances and Skirmishes
  [7] = 11; -- Item Advancement
  [8] = 14; -- Crafting
  [9] = 6; -- Currency
};

