-- auto-generated by Cube's TitanBarWalletItemsGenerator tool at 2024-08-13 18:37:46 UTC
_G.WalletItems = {
  [1879092849] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Broken Arnorian Pauldrons
  [1879092850] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Broken Arnorian Shirt
  [1879092851] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Broken Arnorian Leggings
  [1879092852] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Arnorian Armour Fragments
  [1879092853] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Battered Arnorian Armour
  [1879093652] = { ["itemClass"] = 27; ["category"] = 13; ["shared"] = true; }; -- Bottle of Ale
  [1879093653] = { ["itemClass"] = 27; ["category"] = 13; ["shared"] = true; }; -- Keg of Cram
  [1879095717] = { ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Dull Spirit Stone
  [1879095718] = { ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Glimmering Spirit Stone
  [1879095719] = { ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Luminous Spirit Stone
  [1879098157] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Opal
  [1879098158] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Sparkling Diamond
  [1879098159] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Fiery Quartz
  [1879098160] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dazzling Emerald
  [1879098161] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Near Perfect Sapphire
  [1879098162] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Glinting Amethyst
  [1879098163] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Glowing Red Ruby
  [1879098172] = { ["itemClass"] = 178; ["category"] = 10; }; -- Rift-iron Coin
  [1879098260] = { ["itemClass"] = 178; ["category"] = 13; }; -- Faultless Geode
  [1879098261] = { ["itemClass"] = 178; ["category"] = 13; }; -- Pristine Geode
  [1879098262] = { ["itemClass"] = 178; ["category"] = 13; }; -- Cracked Geode
  [1879098263] = { ["itemClass"] = 178; ["category"] = 13; }; -- Elegant Scroll
  [1879098264] = { ["itemClass"] = 178; ["category"] = 13; }; -- Well-written Scroll
  [1879098265] = { ["itemClass"] = 178; ["category"] = 13; }; -- Unimpressive Scroll
  [1879098266] = { ["itemClass"] = 178; ["category"] = 13; }; -- Large Apple
  [1879098267] = { ["itemClass"] = 178; ["category"] = 13; }; -- Medium Apple
  [1879098268] = { ["itemClass"] = 178; ["category"] = 13; }; -- Small Apple
  [1879098269] = { ["itemClass"] = 178; ["category"] = 13; }; -- Large Pumpkin
  [1879098270] = { ["itemClass"] = 178; ["category"] = 13; }; -- Medium Pumpkin
  [1879098271] = { ["itemClass"] = 178; ["category"] = 13; }; -- Small Pumpkin
  [1879098272] = { ["itemClass"] = 178; ["category"] = 13; }; -- Fall Festival Token
  [1879098864] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Barghest Corpse
  [1879098865] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Black-bear Corpse
  [1879098866] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Brown-bear Corpse
  [1879098867] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Cave-troll Head
  [1879098868] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Warg Corpse
  [1879098869] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged White-wolf Corpse
  [1879099326] = { ["itemClass"] = 178; ["category"] = 10; }; -- Obsidian Rock-shard
  [1879099340] = { ["itemClass"] = 178; ["category"] = 10; }; -- Scrap of Rift-iron Ore
  [1879101765] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Harvestmath Race Token
  [1879103035] = { ["itemClass"] = 178; ["category"] = 12; }; -- Arm of Lagmas
  [1879103036] = { ["itemClass"] = 178; ["category"] = 12; }; -- Remmenaeg's Armour
  [1879103037] = { ["itemClass"] = 178; ["category"] = 12; }; -- Ivar's Banner
  [1879103038] = { ["itemClass"] = 178; ["category"] = 12; }; -- Naruhel's Dress
  [1879103039] = { ["itemClass"] = 178; ["category"] = 12; }; -- Head of Bogbereth
  [1879103040] = { ["itemClass"] = 178; ["category"] = 12; }; -- Sambrog's Helm
  [1879103041] = { ["itemClass"] = 178; ["category"] = 12; }; -- The Mirror of Mordirith
  [1879103042] = { ["itemClass"] = 178; ["category"] = 12; }; -- Ferndur's Skull
  [1879103043] = { ["itemClass"] = 178; ["category"] = 12; }; -- The Skull of Thorog
  [1879103044] = { ["itemClass"] = 178; ["category"] = 12; }; -- Udunion's Swords
  [1879103045] = { ["itemClass"] = 178; ["category"] = 12; }; -- Tentacle of Helchgam
  [1879103078] = { ["itemClass"] = 178; ["category"] = 12; }; -- Thaurlach's Blade
  [1879103239] = { ["itemClass"] = 178; ["category"] = 13; }; -- Violet
  [1879103240] = { ["itemClass"] = 178; ["category"] = 13; }; -- White Honeysuckle
  [1879103241] = { ["itemClass"] = 178; ["category"] = 13; }; -- Primrose
  [1879103242] = { ["itemClass"] = 178; ["category"] = 13; }; -- Marigold
  [1879109296] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Tin Token
  [1879109297] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Iron Token
  [1879109298] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Silver Token
  [1879109299] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Gold Token
  [1879109300] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Platinum Token
  [1879109999] = { ["itemClass"] = 102; ["category"] = 12; }; -- Cunning Catfish
  [1879110000] = { ["itemClass"] = 102; ["category"] = 12; }; -- Superb Smelt
  [1879110002] = { ["itemClass"] = 102; ["category"] = 12; }; -- Big Mouth Bass
  [1879110003] = { ["itemClass"] = 102; ["category"] = 12; }; -- Barbarous Barbel
  [1879110004] = { ["itemClass"] = 102; ["category"] = 12; }; -- Fantastic Flounder
  [1879110005] = { ["itemClass"] = 102; ["category"] = 12; }; -- Gleaming Grayling
  [1879110006] = { ["itemClass"] = 102; ["category"] = 12; }; -- Huge Houting
  [1879110007] = { ["itemClass"] = 102; ["category"] = 12; }; -- Nasty Nine-spined Stickleback
  [1879110008] = { ["itemClass"] = 102; ["category"] = 12; }; -- Colourful Charr
  [1879110009] = { ["itemClass"] = 102; ["category"] = 12; }; -- Brawny Bullhead
  [1879110010] = { ["itemClass"] = 102; ["category"] = 12; }; -- Giant Goldfish
  [1879110011] = { ["itemClass"] = 102; ["category"] = 12; }; -- Delightful Dace
  [1879110012] = { ["itemClass"] = 102; ["category"] = 12; }; -- Great Golden Mullet
  [1879110013] = { ["itemClass"] = 102; ["category"] = 12; }; -- Perfect Perch
  [1879110014] = { ["itemClass"] = 102; ["category"] = 12; }; -- Magnificent Minnow
  [1879110015] = { ["itemClass"] = 102; ["category"] = 12; }; -- Tricky Three-spined Stickleback
  [1879110016] = { ["itemClass"] = 102; ["category"] = 12; }; -- Ruthless Rudd
  [1879110017] = { ["itemClass"] = 102; ["category"] = 12; }; -- Perfect Pike
  [1879110018] = { ["itemClass"] = 102; ["category"] = 12; }; -- Bright Bitterling
  [1879110019] = { ["itemClass"] = 102; ["category"] = 12; }; -- Courageous Carp
  [1879110182] = { ["itemClass"] = 102; ["category"] = 12; }; -- 6-pound Salmon
  [1879110183] = { ["itemClass"] = 102; ["category"] = 12; }; -- 30-pound Salmon
  [1879110184] = { ["itemClass"] = 102; ["category"] = 12; }; -- 20-pound Salmon
  [1879110185] = { ["itemClass"] = 102; ["category"] = 12; }; -- 4-pound Salmon
  [1879110186] = { ["itemClass"] = 102; ["category"] = 12; }; -- 10-pound Salmon
  [1879110187] = { ["itemClass"] = 102; ["category"] = 12; }; -- 15-pound Salmon
  [1879110188] = { ["itemClass"] = 27; ["category"] = 12; }; -- 50-pound Salmon
  [1879110189] = { ["itemClass"] = 102; ["category"] = 12; }; -- 40-pound Salmon
  [1879110190] = { ["itemClass"] = 102; ["category"] = 12; }; -- 2-pound Salmon
  [1879110285] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Tundra Bear Corpse
  [1879110286] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Winter-tusk Skull
  [1879110287] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Frost-antler Head
  [1879110288] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Sabre-tooth Corpse
  [1879110289] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Wolverine Corpse
  [1879110290] = { ["itemClass"] = 178; ["category"] = 12; }; -- Undamaged Winter-worm Corpse
  [1879112716] = { ["itemClass"] = 178; ["category"] = 10; }; -- Broken Signet
  [1879112717] = { ["itemClass"] = 178; ["category"] = 10; }; -- Vile Bronze Coin
  [1879112718] = { ["itemClass"] = 178; ["category"] = 10; }; -- Ring of Devotion
  [1879112719] = { ["itemClass"] = 178; ["category"] = 10; }; -- Banner of the Iron Crown
  [1879112720] = { ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Triumph
  [1879112721] = { ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Victory
  [1879112722] = { ["itemClass"] = 178; ["category"] = 10; }; -- Emblem of the Oath Holder
  [1879115674] = { ["itemClass"] = 27; ["category"] = 8; }; -- Amberjack
  [1879115675] = { ["itemClass"] = 27; ["category"] = 8; }; -- Luillim
  [1879115676] = { ["itemClass"] = 27; ["category"] = 8; }; -- Drum
  [1879115678] = { ["itemClass"] = 178; ["category"] = 8; }; -- Celebhal
  [1879115679] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Summer Festival Token
  [1879115708] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Summerfest Race Token
  [1879115920] = { ["itemClass"] = 178; ["category"] = 8; }; -- Medium Fish
  [1879115923] = { ["itemClass"] = 178; ["category"] = 8; }; -- Large Fish
  [1879115924] = { ["itemClass"] = 178; ["category"] = 8; }; -- Starry Flounder
  [1879115925] = { ["itemClass"] = 178; ["category"] = 8; }; -- Silver Haddock
  [1879115927] = { ["itemClass"] = 178; ["category"] = 8; }; -- Small Fish
  [1879115929] = { ["itemClass"] = 178; ["category"] = 8; }; -- Golden Redfish
  [1879116031] = { ["itemClass"] = 178; ["category"] = 13; }; -- Man Mask Token
  [1879116035] = { ["itemClass"] = 178; ["category"] = 13; }; -- Elf Mask Token
  [1879116039] = { ["itemClass"] = 178; ["category"] = 13; }; -- Hobbit Mask Token
  [1879116043] = { ["itemClass"] = 178; ["category"] = 13; }; -- Dwarf Mask Token
  [1879124334] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Thorog's Fang
  [1879124335] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Thorog's Claw
  [1879124336] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Thorog's Horn
  [1879124337] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Scrap of Storvâgûn's Armour
  [1879124338] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Zaudru's Stinger
  [1879124339] = { ["itemClass"] = 178; ["category"] = 10; ["old"] = true; }; -- Amulet of the Witch-King
  [1879124340] = { ["itemClass"] = 178; ["category"] = 10; }; -- Scrap of Wisdán's Cloak
  [1879124341] = { ["itemClass"] = 178; ["category"] = 10; }; -- Breastplate of Gruglok
  [1879124342] = { ["itemClass"] = 178; ["category"] = 10; }; -- Blade of Dúnachar
  [1879124343] = { ["itemClass"] = 178; ["category"] = 10; }; -- Udúnion's Horn
  [1879124344] = { ["itemClass"] = 178; ["category"] = 10; }; -- Cloven Helm of Lagmas
  [1879124345] = { ["itemClass"] = 178; ["category"] = 10; }; -- Helchgam's Beak
  [1879124406] = { ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Triumph
  [1879124455] = { ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Rhunendin Victory
  [1879124456] = { ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Rammas Deluon Victory
  [1879124457] = { ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Aughaire Victory
  [1879125194] = { ["itemClass"] = 178; ["category"] = 10; }; -- Vile Silver Coin
  [1879135353] = { ["itemClass"] = 178; ["category"] = 11; }; -- Hundi's Token
  [1879135973] = { ["itemClass"] = 178; ["category"] = 11; }; -- Snári's Token
  [1879138033] = { ["itemClass"] = 178; ["category"] = 10; }; -- Writ of Angmar
  [1879138034] = { ["itemClass"] = 178; ["category"] = 10; }; -- Writ of Annúminas
  [1879138035] = { ["itemClass"] = 178; ["category"] = 10; }; -- Writ of Helegrod
  [1879143481] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Courage
  [1879143482] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Courage
  [1879143483] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Courage
  [1879143484] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Silver Coin of Courage
  [1879143485] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Silver Coin of Courage
  [1879143486] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Silver Coin of Courage
  [1879143487] = { ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Courage
  [1879143500] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Hand
  [1879143501] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Resolve
  [1879143502] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Strength
  [1879143503] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Heart
  [1879143504] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Copper Coin of Spirit
  [1879143505] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Hand
  [1879143506] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Resolve
  [1879143507] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Strength
  [1879143508] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Heart
  [1879143509] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Copper Coin of Spirit
  [1879143510] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Hand
  [1879143511] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Resolve
  [1879143512] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Strength
  [1879143513] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Heart
  [1879143514] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Copper Coin of Spirit
  [1879143537] = { ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Hand
  [1879143538] = { ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Resolve
  [1879143539] = { ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Strength
  [1879143540] = { ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Heart
  [1879143541] = { ["itemClass"] = 178; ["category"] = 10; }; -- Platinum Coin of Spirit
  [1879143542] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Silver Coin of Hand
  [1879143543] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Silver Coin of Resolve
  [1879143544] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Silver Coin of Hand
  [1879143545] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Silver Coin of Resolve
  [1879143546] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Silver Coin of Hand
  [1879143547] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Silver Coin of Resolve
  [1879143548] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Gold Coin of Strength
  [1879143549] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Gold Coin of Heart
  [1879143550] = { ["itemClass"] = 178; ["category"] = 10; }; -- Náin's Gold Coin of Spirit
  [1879143551] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Gold Coin of Strength
  [1879143552] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Gold Coin of Heart
  [1879143553] = { ["itemClass"] = 178; ["category"] = 10; }; -- Durin's Gold Coin of Spirit
  [1879143554] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Gold Coin of Strength
  [1879143555] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Gold Coin of Heart
  [1879143556] = { ["itemClass"] = 178; ["category"] = 10; }; -- Balin's Gold Coin of Spirit
  [1879145158] = { ["itemClass"] = 178; ["category"] = 11; }; -- Khuzdul Tablets
  [1879145168] = { ["itemClass"] = 178; ["category"] = 11; }; -- Rusted Dwarf Tools
  [1879145790] = { ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Tyrant's Crest
  [1879145791] = { ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Chieftain's Brooch
  [1879145796] = { ["itemClass"] = 178; ["category"] = 16; ["old"] = true; }; -- Brilliant Spirit Stone
  [1879147329] = { ["itemClass"] = 178; ["category"] = 10; }; -- Mark of Victory
  [1879147798] = { ["itemClass"] = 178; ["category"] = 12; }; -- Kranklûk's Hammer
  [1879147799] = { ["itemClass"] = 178; ["category"] = 12; }; -- Morhûn's Gemstone
  [1879147800] = { ["itemClass"] = 178; ["category"] = 12; }; -- Fungal Mushroom
  [1879147801] = { ["itemClass"] = 178; ["category"] = 12; }; -- Gurvand's Head
  [1879147802] = { ["itemClass"] = 178; ["category"] = 12; }; -- Stinger of Brúmbereth
  [1879147803] = { ["itemClass"] = 178; ["category"] = 12; }; -- Grimreaver
  [1879147804] = { ["itemClass"] = 178; ["category"] = 12; }; -- Egg of the Mistress
  [1879148394] = { ["itemClass"] = 178; ["category"] = 12; }; -- Shield of the White Hand
  [1879148395] = { ["itemClass"] = 178; ["category"] = 12; }; -- White Hand Helm and Feathers
  [1879148396] = { ["itemClass"] = 178; ["category"] = 12; }; -- Igash's Trinket
  [1879148397] = { ["itemClass"] = 178; ["category"] = 12; }; -- The Beast's Drum
  [1879148398] = { ["itemClass"] = 178; ["category"] = 12; }; -- Gothghaash's Symbol
  [1879148399] = { ["itemClass"] = 178; ["category"] = 12; }; -- Glothrok's Token
  [1879149147] = { ["itemClass"] = 178; ["category"] = 10; }; -- Iron Coin of Knowledge
  [1879149148] = { ["itemClass"] = 178; ["category"] = 10; }; -- Iron Coin of Fortitude
  [1879149371] = { ["itemClass"] = 178; ["category"] = 12; }; -- General Talug's Armour
  [1879149481] = { ["itemClass"] = 178; ["category"] = 12; }; -- Watcher's Token
  [1879149757] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Old Winter Festival Token
  [1879149799] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Yule Horse Race Token
  [1879150061] = { ["itemClass"] = 178; ["category"] = 14; }; -- Iron Garrison Resource Token
  [1879150131] = { ["itemClass"] = 178; ["category"] = 15; }; -- Lothlórien Gold Leaf
  [1879150132] = { ["itemClass"] = 178; ["category"] = 15; }; -- Lothlórien Silver Branch
  [1879151374] = { ["itemClass"] = 178; ["category"] = 8; }; -- Token of Salutation
  [1879151743] = { ["itemClass"] = 178; ["category"] = 13; }; -- Spring Leaf
  [1879151887] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Hand
  [1879151888] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Courage
  [1879151889] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Spirit
  [1879151904] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Strength
  [1879151905] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Heart
  [1879151908] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Greater Elf-stone of Resolve
  [1879151992] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Glistening Elf-stone of Resolve
  [1879151996] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Uncut Elf-stone of Strength
  [1879151999] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Uncut Elf-stone of Hand
  [1879152000] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Glistening Elf-stone of Hand
  [1879152004] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Elf-stone of Hand
  [1879152011] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Glistening Elf-stone of Strength
  [1879152017] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Uncut Elf-stone of Resolve
  [1879152023] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Elf-stone of Strength
  [1879152025] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Elf-stone of Resolve
  [1879155363] = { ["itemClass"] = 178; ["category"] = 11; }; -- Bright Emblem of Nimrodel
  [1879155768] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Skirmish Mark
  [1879159674] = { ["itemClass"] = 178; ["category"] = 12; }; -- Nornúan's Head
  [1879159675] = { ["itemClass"] = 178; ["category"] = 12; }; -- Small Turtle Shell
  [1879160876] = { ["itemClass"] = 178; ["category"] = 12; }; -- Thaguzg's Armour
  [1879160877] = { ["itemClass"] = 178; ["category"] = 12; }; -- The Blind One's Skull
  [1879160878] = { ["itemClass"] = 178; ["category"] = 12; }; -- Zholuga's Head
  [1879160879] = { ["itemClass"] = 178; ["category"] = 12; }; -- Istûm's Head
  [1879160880] = { ["itemClass"] = 178; ["category"] = 12; }; -- Flâgît's Head
  [1879160881] = { ["itemClass"] = 178; ["category"] = 12; }; -- Ergoth's Wings
  [1879160882] = { ["itemClass"] = 178; ["category"] = 12; }; -- Caerlug's Arm
  [1879167037] = { ["itemClass"] = 178; ["category"] = 14; }; -- Ceremonial Dwarf-axe
  [1879167038] = { ["itemClass"] = 178; ["category"] = 14; }; -- Black-wood Bow
  [1879167039] = { ["itemClass"] = 178; ["category"] = 14; }; -- 'Battle of Dagorlad' Tapestry
  [1879167040] = { ["itemClass"] = 178; ["category"] = 14; }; -- Record of Durin
  [1879167041] = { ["itemClass"] = 178; ["category"] = 14; }; -- Dragon-helm
  [1879167042] = { ["itemClass"] = 178; ["category"] = 14; }; -- Royal Crown
  [1879167043] = { ["itemClass"] = 178; ["category"] = 14; }; -- Record of the Elf-lords
  [1879167044] = { ["itemClass"] = 178; ["category"] = 14; }; -- Feast of Harvestmath
  [1879167045] = { ["itemClass"] = 178; ["category"] = 14; }; -- Númenórean Sceptre
  [1879167046] = { ["itemClass"] = 178; ["category"] = 14; }; -- Silver Basin
  [1879167047] = { ["itemClass"] = 178; ["category"] = 14; }; -- Feast of Lithe
  [1879167049] = { ["itemClass"] = 178; ["category"] = 14; }; -- Record of the Race of Man
  [1879167050] = { ["itemClass"] = 178; ["category"] = 14; }; -- Feast of Ethuilwereth
  [1879167051] = { ["itemClass"] = 178; ["category"] = 14; }; -- Red Arrow
  [1879167053] = { ["itemClass"] = 178; ["category"] = 14; }; -- 'Battle of Five Armies' Tapestry
  [1879167054] = { ["itemClass"] = 178; ["category"] = 14; }; -- Engraved Elf-blade
  [1879167055] = { ["itemClass"] = 178; ["category"] = 14; }; -- Statue of Elendil
  [1879167058] = { ["itemClass"] = 178; ["category"] = 14; }; -- Dúnedain Star
  [1879167059] = { ["itemClass"] = 178; ["category"] = 14; }; -- Beryl Pendant
  [1879167060] = { ["itemClass"] = 178; ["category"] = 14; }; -- 'Siege of Barad-dûr' Tapestry
  [1879167062] = { ["itemClass"] = 178; ["category"] = 14; }; -- Royal Circlet
  [1879167627] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Medallion of Moria
  [1879167628] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Medallion of Lothlórien
  [1879167629] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; ["old"] = true; }; -- Medallion of Dol Guldur
  [1879172361] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Spirit
  [1879172362] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Resolve
  [1879172363] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Heart
  [1879172364] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Hand
  [1879172365] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Courage
  [1879172366] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Dark Emblem of Strength
  [1879172834] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Eglain Token
  [1879173003] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Springfest Race Token
  [1879174739] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Document of Mount Ownership
  [1879175320] = { ["itemClass"] = 178; ["category"] = 15; }; -- Malledhrim Gold Star Emblem
  [1879175321] = { ["itemClass"] = 178; ["category"] = 15; }; -- Malledhrim Bronze Feather
  [1879179430] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran's First Mark
  [1879179431] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- First Mark
  [1879179432] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran's Second Mark
  [1879179433] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Second Mark
  [1879179434] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran's Third Mark
  [1879179435] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Third Mark
  [1879179436] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Recruit's Mark
  [1879179439] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Esquire's Mark
  [1879179440] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Guardsman's Mark
  [1879180935] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Naillan Campaign Mark
  [1879180936] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Cannuilan Campaign Mark
  [1879180937] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Eruilan Campaign Mark
  [1879180938] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Adlan Campaign Mark
  [1879180964] = { ["itemClass"] = 178; ["category"] = 12; }; -- Black Robes
  [1879181000] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Footman's Mark
  [1879181001] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran Guardsman's Mark
  [1879181002] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran Esquire's Mark
  [1879181003] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran Footman's Mark
  [1879181948] = { ["itemClass"] = 178; ["category"] = 15; }; -- Silver Token of the Wilds
  [1879181950] = { ["itemClass"] = 178; ["category"] = 15; }; -- Golden Token of the Wilds
  [1879183133] = { ["itemClass"] = 178; ["category"] = 13; }; -- Badge of Dishonour
  [1879183648] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Lefnuilan Campaign Mark
  [1879185000] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Ancient Silver Token
  [1879185001] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Ancient Gold Token
  [1879185086] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Eregion Mark
  [1879185087] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Annúminas Mark
  [1879185088] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Helegrod Mark
  [1879185098] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Superior Third Mark
  [1879185136] = { ["itemClass"] = 178; ["category"] = 13; }; -- Badge of Taste
  [1879185893] = { ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Remove Dread Tome
  [1879185909] = { ["itemClass"] = 173; ["category"] = 8; ["old"] = true; }; -- Revival Tome
  [1879186958] = { ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Apprentice Ingredient Pack
  [1879186959] = { ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Journeyman Ingredient Pack
  [1879186960] = { ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Artisan Ingredient Pack
  [1879186961] = { ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Master Ingredient Pack
  [1879186962] = { ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Supreme Ingredient Pack
  [1879186963] = { ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Expert Ingredient Pack
  [1879191713] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Great Barrow Mark
  [1879197800] = { ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Upgrade Task Limit (+1)
  [1879199409] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Frostbluff Coin
  [1879200577] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; ["old"] = true; }; -- Medallion of the North-men
  [1879200721] = { ["itemClass"] = 178; ["category"] = 13; }; -- Anniversary Token
  [1879201266] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Anniversary Race Token
  [1879201840] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Boots Medallion
  [1879201845] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Helmet Medallion
  [1879201846] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Boots Medallion
  [1879201854] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Shoulder-guards Medallion
  [1879201856] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Helmet Medallion
  [1879201858] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Breastplate Medallion
  [1879201860] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Leg-guards Medallion
  [1879201868] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Leg-guards Medallion
  [1879201869] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Heroes' Steel Gauntlets Medallion
  [1879201874] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Gauntlets Medallion
  [1879201875] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Shoulder-guards Medallion
  [1879201878] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Western Aspirants' Red Breastplate Medallion
  [1879201943] = { ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Upgrade Task Limit (+1)
  [1879201944] = { ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Upgrade Task Limit (+1)
  [1879201945] = { ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Upgrade Task Limit (+1)
  [1879201946] = { ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Upgrade Task Limit (+1)
  [1879202375] = { ["itemClass"] = 178; ["category"] = 11; ["shared"] = true; }; -- Shard
  [1879205077] = { ["itemClass"] = 178; ["category"] = 10; }; -- Gloves Token
  [1879205082] = { ["itemClass"] = 178; ["category"] = 10; }; -- Leg-guards Token
  [1879205083] = { ["itemClass"] = 178; ["category"] = 10; }; -- Shoulders Token
  [1879205086] = { ["itemClass"] = 178; ["category"] = 10; }; -- Helm Token
  [1879205088] = { ["itemClass"] = 178; ["category"] = 10; }; -- Breastplate Token
  [1879205098] = { ["itemClass"] = 178; ["category"] = 10; }; -- Boots Token
  [1879205437] = { ["itemClass"] = 178; ["category"] = 15; }; -- Bronze Arnorian Coin
  [1879205438] = { ["itemClass"] = 178; ["category"] = 15; }; -- Silver Arnorian Coin
  [1879206049] = { ["itemClass"] = 178; ["category"] = 13; }; -- Buried Treasure Token
  [1879206113] = { ["itemClass"] = 178; ["category"] = 12; }; -- Flaming Shadow
  [1879206114] = { ["itemClass"] = 178; ["category"] = 12; }; -- Red Sapped Huorn Limb
  [1879206115] = { ["itemClass"] = 178; ["category"] = 12; }; -- White Sapped Huorn Limb
  [1879206610] = { ["itemClass"] = 178; ["category"] = 13; }; -- Token Fish
  [1879206611] = { ["itemClass"] = 178; ["category"] = 13; }; -- Bad Fish
  [1879206612] = { ["itemClass"] = 178; ["category"] = 13; }; -- Big Fish
  [1879206613] = { ["itemClass"] = 178; ["category"] = 13; }; -- Puny Fish
  [1879206672] = { ["itemClass"] = 178; ["category"] = 13; }; -- Easy Fish
  [1879206673] = { ["itemClass"] = 178; ["category"] = 13; }; -- Simple Fish
  [1879206674] = { ["itemClass"] = 178; ["category"] = 13; }; -- Possible Fish
  [1879206675] = { ["itemClass"] = 178; ["category"] = 13; }; -- Tricky Fish
  [1879206676] = { ["itemClass"] = 178; ["category"] = 13; }; -- Unlikely Fish
  [1879206848] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Race Token
  [1879207368] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Enguilan Campaign Mark
  [1879207894] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Halls of Night Mark
  [1879207904] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Inn of the Forsaken Mark
  [1879209189] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Odothuilan Campaign Mark
  [1879217575] = { ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Westfold Ingredient Pack
  [1879218744] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran's Fourth Mark
  [1879218745] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Superior Fourth Mark
  [1879218746] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Fourth Mark
  [1879218928] = { ["itemClass"] = 178; ["category"] = 10; }; -- Scorched Shoulder-guard Token
  [1879218942] = { ["itemClass"] = 178; ["category"] = 10; }; -- Scorched Helm Token
  [1879221222] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Veteran Sergeant-at-Arms Mark
  [1879221259] = { ["itemClass"] = 177; ["category"] = 1; ["old"] = true; }; -- Sergeant-at-Arms Mark
  [1879222280] = { ["itemClass"] = 178; ["category"] = 12; }; -- Phial of Eternal Flame
  [1879222281] = { ["itemClass"] = 178; ["category"] = 12; }; -- Battered Scale
  [1879223715] = { ["itemClass"] = 178; ["category"] = 13; }; -- Farmers Faire Token
  [1879224343] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Mark
  [1879224344] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Medallion
  [1879224345] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Seal
  [1879226347] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Orthanc Sigil-fragment
  [1879227344] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Farmers Faire Race Token
  [1879227924] = { ["itemClass"] = 178; ["category"] = 12; }; -- Orrery-fragment
  [1879227925] = { ["itemClass"] = 178; ["category"] = 12; }; -- Chipped Throne-fragment
  [1879227926] = { ["itemClass"] = 178; ["category"] = 12; }; -- Shattered Ring-fragment
  [1879229676] = { ["itemClass"] = 178; ["category"] = 15; }; -- Golden Token of the Anduin
  [1879229677] = { ["itemClass"] = 178; ["category"] = 15; }; -- Silver Token of the Anduin
  [1879229829] = { ["itemClass"] = 178; ["category"] = 14; }; -- Grand Feast of Ethuilwereth
  [1879229830] = { ["itemClass"] = 178; ["category"] = 14; }; -- Grand Feast of Lithe
  [1879229832] = { ["itemClass"] = 178; ["category"] = 14; }; -- Elaborate Dúnedain Star
  [1879229833] = { ["itemClass"] = 178; ["category"] = 14; }; -- Elaborate Royal Circlet
  [1879229835] = { ["itemClass"] = 178; ["category"] = 14; }; -- Adorned Royal Crown
  [1879229836] = { ["itemClass"] = 178; ["category"] = 14; }; -- Adorned Dragon-helm
  [1879229838] = { ["itemClass"] = 178; ["category"] = 14; }; -- Illuminated Record of the Race of Man
  [1879229839] = { ["itemClass"] = 178; ["category"] = 14; }; -- Illuminated Record of the Elf-lords
  [1879229841] = { ["itemClass"] = 178; ["category"] = 14; }; -- Embroidered 'Battle of Five Armies' Tapestry
  [1879229842] = { ["itemClass"] = 178; ["category"] = 14; }; -- Embroidered 'Battle of Dagorlad' Tapestry
  [1879229844] = { ["itemClass"] = 178; ["category"] = 14; }; -- Flawless Ceremonial Dwarf-axe
  [1879229845] = { ["itemClass"] = 178; ["category"] = 14; }; -- Flawless Númenórean Sceptre
  [1879229847] = { ["itemClass"] = 178; ["category"] = 14; }; -- Engraved Red Arrow
  [1879229848] = { ["itemClass"] = 178; ["category"] = 14; }; -- Engraved Statue of Elendil
  [1879230183] = { ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Commendation
  [1879232299] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Unhatched Spider Egg
  [1879233822] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Honorary Postman's Badge
  [1879234223] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Calenard Token
  [1879234649] = { ["itemClass"] = 178; ["category"] = 13; }; -- Sigil of Dedication
  [1879237261] = { ["itemClass"] = 178; ["category"] = 15; }; -- Silver Token of the Riddermark
  [1879237278] = { ["itemClass"] = 178; ["category"] = 15; }; -- Golden Token of the Riddermark
  [1879237349] = { ["itemClass"] = 27; ["category"] = 15; }; -- Token of Hytbold
  [1879238505] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Festival Ticket
  [1879245065] = { ["itemClass"] = 178; ["category"] = 14; }; -- Token of Effort
  [1879245827] = { ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; ["old"] = true; }; -- Eastemnet Ingredient Pack
  [1879251305] = { ["itemClass"] = 178; ["category"] = 14; }; -- Red Ring
  [1879251306] = { ["itemClass"] = 178; ["category"] = 14; }; -- Feast of Cormarë
  [1879251307] = { ["itemClass"] = 178; ["category"] = 14; }; -- Flawless Annúminas Sceptre
  [1879251308] = { ["itemClass"] = 178; ["category"] = 14; }; -- Horn of Helm Hammerhand
  [1879251309] = { ["itemClass"] = 178; ["category"] = 14; }; -- Embroidered 'Battle of the Hornburg' Tapestry
  [1879251310] = { ["itemClass"] = 178; ["category"] = 14; }; -- Grand Feast of Cormarë
  [1879251311] = { ["itemClass"] = 178; ["category"] = 14; }; -- Illuminated Scroll of Kings
  [1879251312] = { ["itemClass"] = 178; ["category"] = 14; }; -- Gondorian Crown
  [1879251313] = { ["itemClass"] = 178; ["category"] = 14; }; -- Engraved Horn of Helm Hammerhand
  [1879251314] = { ["itemClass"] = 178; ["category"] = 14; }; -- Scroll of Kings
  [1879251315] = { ["itemClass"] = 178; ["category"] = 14; }; -- Annúminas Sceptre
  [1879251316] = { ["itemClass"] = 178; ["category"] = 14; }; -- 'Battle of the Hornburg' Tapestry
  [1879251317] = { ["itemClass"] = 178; ["category"] = 14; }; -- Adorned Gondorian Crown
  [1879251318] = { ["itemClass"] = 178; ["category"] = 14; }; -- Elaborate Red Ring
  [1879255991] = { ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; }; -- Mithril Coin
  [1879256449] = { ["itemClass"] = 27; ["category"] = 13; }; -- Yule Festival Token
  [1879257572] = { ["itemClass"] = 178; ["category"] = 13; }; -- Golden Festival Token
  [1879257626] = { ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Traveller's Writ
  [1879257627] = { ["itemClass"] = 178; ["category"] = 9; ["shared"] = true; ["old"] = true; }; -- Stable-master's Writ
  [1879259420] = { ["itemClass"] = 178; ["category"] = 15; }; -- Wildermore Coin
  [1879259421] = { ["itemClass"] = 178; ["category"] = 15; }; -- Gold Token of Wildermore
  [1879261930] = { ["itemClass"] = 178; ["category"] = 13; ["old"] = true; }; -- Riddermark Token
  [1879269887] = { ["itemClass"] = 178; ["category"] = 15; }; -- Warband Token of Wildermore
  [1879271112] = { ["itemClass"] = 178; ["category"] = 15; }; -- Westemnet Iron Coin
  [1879277247] = { ["itemClass"] = 173; ["category"] = 14; ["shared"] = true; }; -- Universal Ingredient Pack
  [1879277688] = { ["itemClass"] = 178; ["category"] = 14; }; -- 'Battle of the Field of Celebrant' Tapestry
  [1879277689] = { ["itemClass"] = 178; ["category"] = 14; }; -- Horn of the Mark
  [1879277690] = { ["itemClass"] = 178; ["category"] = 14; }; -- Embroidered 'Battle of the Field of Celebrant' Tapestry
  [1879277691] = { ["itemClass"] = 178; ["category"] = 14; }; -- Grand Feast of Yáviérë
  [1879277692] = { ["itemClass"] = 178; ["category"] = 14; }; -- Necklace of Emeralds
  [1879277693] = { ["itemClass"] = 178; ["category"] = 14; }; -- Black Key
  [1879277694] = { ["itemClass"] = 178; ["category"] = 14; }; -- Adorned Black Key
  [1879277695] = { ["itemClass"] = 178; ["category"] = 14; }; -- Chronicle of Cirion and Eorl
  [1879277696] = { ["itemClass"] = 178; ["category"] = 14; }; -- Illuminated Chronicle of Cirion and Eorl
  [1879277697] = { ["itemClass"] = 178; ["category"] = 14; }; -- Fierce Sword
  [1879277698] = { ["itemClass"] = 178; ["category"] = 14; }; -- Flawless Fierce Sword
  [1879277699] = { ["itemClass"] = 178; ["category"] = 14; }; -- Engraved Horn of the Mark
  [1879277700] = { ["itemClass"] = 178; ["category"] = 14; }; -- Elaborate Necklace of Emeralds
  [1879277701] = { ["itemClass"] = 178; ["category"] = 14; }; -- Feast of Yáviérë
  [1879278927] = { ["itemClass"] = 27; ["category"] = 13; ["shared"] = true; ["old"] = true; }; -- Bounder's Token
  [1879302681] = { ["itemClass"] = 178; ["category"] = 14; }; -- Receipt of Armament Exchange
  [1879303013] = { ["itemClass"] = 178; ["category"] = 15; }; -- Fangorn Leaf
  [1879303343] = { ["itemClass"] = 178; ["category"] = 8; }; -- Steel Token
  [1879306057] = { ["itemClass"] = 178; ["category"] = 15; }; -- Amroth Silver Piece
  [1879306058] = { ["itemClass"] = 178; ["category"] = 15; }; -- East Gondor Silver Piece
  [1879314933] = { ["itemClass"] = 178; ["category"] = 15; }; -- Central Gondor Silver Piece
  [1879318665] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Star of Merit
  [1879320706] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Gift-giver's Brand
  [1879321808] = { ["itemClass"] = 178; ["category"] = 15; }; -- Bingo Badge
  [1879324717] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Morgul Crest
  [1879325632] = { ["itemClass"] = 178; ["category"] = 15; }; -- Rhosgobel Oak Leaf
  [1879325664] = { ["itemClass"] = 178; ["category"] = 11; ["shared"] = true; }; -- Legendary Item XP Rune
  [1879326936] = { ["itemClass"] = 178; ["category"] = 15; }; -- Minas Tirith - Smiths' Token
  [1879326937] = { ["itemClass"] = 178; ["category"] = 15; }; -- Minas Tirith Silver Piece
  [1879326944] = { ["itemClass"] = 178; ["category"] = 15; }; -- Minas Tirith - Builders' Token
  [1879329799] = { ["itemClass"] = 178; ["category"] = 15; }; -- Minas Tirith - Burgsmen's Token
  [1879332436] = { ["itemClass"] = 178; ["category"] = 10; }; -- Long-lost Coin
  [1879333869] = { ["itemClass"] = 27; ["category"] = 15; }; -- Host of the West Silver Piece
  [1879335251] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Helmet of the Pelennor Fields
  [1879335252] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Gauntlets of the Pelennor Fields
  [1879335253] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Bracelet of the Pelennor Fields
  [1879335254] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Tarnished Ring of the Pelennor Fields
  [1879335255] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Reclaimed Pelennor Defender's Gear
  [1879335256] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Earring of the Pelennor Fields
  [1879335257] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Leg-guards of the Pelennor Fields
  [1879335258] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Shoulders of the Pelennor Fields
  [1879335259] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Cracked Pocket-mirror
  [1879335260] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Tarnished Necklace of the Pelennor Fields
  [1879335261] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Boots of the Pelennor Fields
  [1879335262] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Helmet of the Pelennor Fields
  [1879335263] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Leg-guards of the Pelennor Fields
  [1879335264] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Tarnished Bracelet of the Pelennor Fields
  [1879335265] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Battle-damaged Equipment of the Pelennor Fields
  [1879335266] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Boots of the Pelennor Fields
  [1879335267] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Necklace of the Pelennor Fields
  [1879335268] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Worn Chestplate of the Pelennor Fields
  [1879335269] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Tarnished Earring of the Pelennor Fields
  [1879335270] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Pristine Ring of the Pelennor Fields
  [1879335271] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Star-laden Tapestry
  [1879335272] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Ancient Ithil-coin
  [1879335273] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Gauntlets of the Pelennor Fields
  [1879335274] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Chestplate of the Pelennor Fields
  [1879335275] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Masterwork Shoulders of the Pelennor Fields
  [1879338037] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Crimson Extract
  [1879338038] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Umber Extract
  [1879338039] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Golden Extract
  [1879338040] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Amber Extract
  [1879338041] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Verdant Extract
  [1879338042] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Sapphire Extract
  [1879338043] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Phial of Violet Extract
  [1879340090] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Officer's Bracelet of the Pelennor Fields
  [1879341063] = { ["itemClass"] = 178; ["category"] = 15; }; -- Ithilien Essence Fragment
  [1879341064] = { ["itemClass"] = 178; ["category"] = 8; }; -- Ithilien Scrap of an Essence Reclamation Scroll
  [1879343050] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Tarnished Sigil of Gondor
  [1879345122] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Gold Signet of the Thandrim
  [1879345125] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Silver Signet of the Thandrim
  [1879352247] = { ["itemClass"] = 27; ["category"] = 6; ["shared"] = true; }; -- Motes of Enchantment
  [1879353887] = { ["itemClass"] = 178; ["category"] = 15; }; -- Token of Service
  [1879361622] = { ["itemClass"] = 178; ["category"] = 8; }; -- Sliver of Black Steel
  [1879361902] = { ["itemClass"] = 178; ["category"] = 13; }; -- Scrap of an Essence Reclamation Scroll
  [1879362402] = { ["itemClass"] = 178; ["category"] = 15; }; -- Token of the Lake and Rivers
  [1879364886] = { ["itemClass"] = 178; ["category"] = 13; }; -- Fragment of a Shadow Essence
  [1879368412] = { ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Rare Vanguard Relic Exchange Token
  [1879368413] = { ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Grand Abyssal Relic Exchange Token
  [1879368414] = { ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Incomparable Vangard Relic Exchange Token
  [1879368415] = { ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Abyssal Relic Exchange Token
  [1879368416] = { ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Greater Abyssal Relic Exchange Token
  [1879368479] = { ["itemClass"] = 27; ["category"] = 15; }; -- Mark of the Longbeards
  [1879368818] = { ["itemClass"] = 178; ["category"] = 10; }; -- Festivity Token
  [1879369175] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Thrâng's Vault Token
  [1879369423] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Newfound Coin
  [1879377205] = { ["itemClass"] = 178; ["category"] = 6; ["shared"] = true; }; -- Embers of Enchantment
  [1879378796] = { ["itemClass"] = 178; ["category"] = 10; }; -- Coin of Grárik
  [1879381191] = { ["itemClass"] = 178; ["category"] = 6; ["shared"] = true; }; -- Figments of Splendour
  [1879383301] = { ["itemClass"] = 178; ["category"] = 8; }; -- Legendary Coin of Angmar
  [1879383302] = { ["itemClass"] = 178; ["category"] = 15; }; -- Himbar Token of Exchange
  [1879385805] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Token of Ill Omens
  [1879385997] = { ["itemClass"] = 27; ["category"] = 15; }; -- Gúlmark
  [1879386515] = { ["itemClass"] = 178; ["category"] = 15; }; -- Vales - Beorning Token
  [1879386518] = { ["itemClass"] = 178; ["category"] = 15; }; -- Vales - Elf Token
  [1879386519] = { ["itemClass"] = 178; ["category"] = 15; }; -- Vales - Woodmen Token
  [1879387494] = { ["itemClass"] = 178; ["category"] = 8; }; -- Legendary Coin of Moria
  [1879389108] = { ["itemClass"] = 178; ["category"] = 8; }; -- Legendary Coin of Mirkwood
  [1879389826] = { ["itemClass"] = 27; ["category"] = 15; ["shared"] = true; }; -- Sigil of Imlad Ithil
  [1879401397] = { ["itemClass"] = 178; ["category"] = 10; }; -- Coin of the Bugan
  [1879403799] = { ["itemClass"] = 178; ["category"] = 15; }; -- Northern Gúlmark
  [1879406105] = { ["itemClass"] = 178; ["category"] = 13; }; -- Midsummer Token
  [1879406458] = { ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Pet Harness
  [1879406459] = { ["itemClass"] = 178; ["category"] = 8; ["shared"] = true; }; -- Steed Halter
  [1879407802] = { ["itemClass"] = 27; ["category"] = 15; }; -- Copper Coin of Gundabad
  [1879410524] = { ["itemClass"] = 27; ["category"] = 14; ["shared"] = true; }; -- Elderslade Supply Pack
  [1879411090] = { ["itemClass"] = 178; ["category"] = 15; }; -- Gabil'akkâ War-mark
  [1879413176] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Mark of the Wilds
  [1879413185] = { ["itemClass"] = 178; ["category"] = 15; }; -- Bree-land Wood-mark
  [1879413574] = { ["itemClass"] = 178; ["category"] = 15; }; -- Zakaf-beshek
  [1879416775] = { ["itemClass"] = 178; ["category"] = 15; }; -- Gundabad Mountain-mark
  [1879416776] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Geode - Agate
  [1879416778] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Geode - Amethyst
  [1879416779] = { ["itemClass"] = 27; ["category"] = 15; }; -- Silver Coin of Gundabad
  [1879416781] = { ["itemClass"] = 178; ["category"] = 15; }; -- Token of the Zhélruka
  [1879416782] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Geode - Quartz
  [1879416787] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Geode - Gypsum
  [1879416791] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Geode - Jasper
  [1879416834] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Token of Resolution
  [1879418432] = { ["itemClass"] = 178; ["category"] = 15; }; -- Token of the Kharum-ubnâr
  [1879418577] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Token of Further Adventure
  [1879424263] = { ["itemClass"] = 178; ["category"] = 11; ["shared"] = true; }; -- Ancient Script
  [1879442894] = { ["itemClass"] = 27; ["category"] = 15; }; -- Copper Bounder's Coin
  [1879443289] = { ["itemClass"] = 178; ["category"] = 15; }; -- Mark of the Angle
  [1879448448] = { ["itemClass"] = 178; ["category"] = 15; }; -- Iron Coin of Cardolan
  [1879452571] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Delving Writ
  [1879454476] = { ["itemClass"] = 178; ["category"] = 15; }; -- Greyflood Mark
  [1879457091] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Sárskillin
  [1879461938] = { ["itemClass"] = 178; ["category"] = 15; }; -- Mark of Renewal
  [1879463586] = { ["itemClass"] = 27; ["category"] = 15; ["shared"] = true; }; -- Token of Heroism
  [1879464288] = { ["itemClass"] = 178; ["category"] = 15; ["shared"] = true; }; -- Hero's Mark
  [1879465763] = { ["itemClass"] = 178; ["category"] = 14; ["shared"] = true; }; -- Participation Ribbon
  [1879465764] = { ["itemClass"] = 178; ["category"] = 14; ["shared"] = true; }; -- Runner-up Ribbon
  [1879465765] = { ["itemClass"] = 178; ["category"] = 14; ["shared"] = true; }; -- Winner Ribbon
  [1879465779] = { ["itemClass"] = 178; ["category"] = 15; }; -- Umbari Tâm
  [1879467015] = { ["itemClass"] = 178; ["category"] = 14; ["shared"] = true; }; -- Luck-stone
  [1879473346] = { ["itemClass"] = 178; ["category"] = 15; }; -- Eagle Bit
  [1879473347] = { ["itemClass"] = 178; ["category"] = 15; }; -- Ledger-keeper Mark
  [1879479402] = { ["itemClass"] = 178; ["category"] = 14; ["shared"] = true; }; -- Umbar Craft Guild Mark
  [1879482783] = { ["itemClass"] = 178; ["category"] = 10; ["shared"] = true; }; -- Menacing Tentacle
};

_G.WalletUsedCategories = {
  [1] = 9; -- Coin
  [2] = 13; -- Festivals and Events
  [3] = 15; -- Landscape
  [4] = 12; -- Taxidermy
  [5] = 8; -- Other
  [6] = 10; -- Instances and Skirmishes
  [7] = 11; -- Item Advancement
  [8] = 14; -- Crafting
  [9] = 6; -- Currency
};

