-- auto-generated by Cube's TitanBarWalletItemsGenerator tool at 2024-07-02 17:34:46 UTC
_G.WalletItemCategories = {
  [1] = "Zeichen";
  [2] = "Aufgabe: Lothlórien";
  [3] = "Aufgabe: Düsterwald";
  [4] = "Jubiläumsmünzen";
  [6] = "Währung";
  [8] = "Sonstige";
  [9] = "Münzen";
  [10] = "Instanzen und Scharmützel";
  [11] = "Gegenstandsverbesserung";
  [12] = "Tierpräparation";
  [13] = "Feste und Veranstaltungen";
  [14] = "Handwerkskunst";
  [15] = "Landschaft";
  [16] = "Monster-spiel";
};

_G.WalletItemCategoryUnknown = "In TitanBar unbekannt";

