-- auto-generated by Cube's TitanBarWalletItemsGenerator tool at 2024-06-25 18:07:45 UTC
_G.WalletItemCategories = {
  [1] = "Marks";
  [2] = "Quest: Lothlórien";
  [3] = "Quest: Mirkwood";
  [4] = "Anniversary Tokens";
  [6] = "Currency";
  [8] = "Other";
  [9] = "Coin";
  [10] = "Instances and Skirmishes";
  [11] = "Item Advancement";
  [12] = "Taxidermy";
  [13] = "Festivals and Events";
  [14] = "Crafting";
  [15] = "Landscape";
  [16] = "Monster Play";
};

