-- auto-generated by Cube's TitanBarWalletItemsGenerator tool at 2024-07-02 17:34:46 UTC
_G.WalletItemCategories = {
  [1] = "Marques";
  [2] = "Quête : Lothlórien";
  [3] = "Quête : Forêt Noire";
  [4] = "Jetons d'anniversaire";
  [6] = "Monnaie";
  [8] = "Autres";
  [9] = "Pièce";
  [10] = "Instances et escarmouches";
  [11] = "Progression d'objet";
  [12] = "Taxidermie";
  [13] = "Festivals et événements";
  [14] = "Artisanat";
  [15] = "Paysage";
  [16] = "Monster Play";
};

_G.WalletItemCategoryUnknown = "Inconnu de TitanBar";

